import { registerCatalog } from "./copy.js";

// What the Worker says in its own voice outside a notification: the reply in
// a channel when a message becomes a decision, a reminder card, a proposal to
// automate, a routine's name and its schedule read aloud. Written by hand in
// the languages below; any other is learned by copy.js on first use.

const EN = {
  "jam.transcript": "Transcript",
  "invite.joined": "{name} joined the workspace. Say hello!",
  "welcome.dm": "Welcome to {team}, {name}! A few things to get you going:\n- Channels on the left hold the team's conversations, one topic each.\n- Write *@AI* to ask your AI anything; it answers in the thread. To have someone decide, send it as a decision (✦).\n- Write *@* and an agent's name to have it research, summarise or draft for you.\n- Messages in other languages are translated into yours automatically.\nAnything else, ask {owner} right here.",
  "welcome.yourTeam": "your team",
  "invite.someone": "Someone new",
  "invite.agentJoined": "The agent “{name}” joined, working for {by}.",
  "agent.noModel": "I can't answer yet: this workspace has no AI model set up. An admin can pick one in Tools.",
  "agent.quota": "You have used today's AI answers. Tomorrow, or Pro, brings more.",
  "agent.failed": "I couldn't answer just now. Try again in a moment.",
  "agent.failedService": "I couldn't answer: the AI service turned the request down. Check the workspace's AI key in Tools → AI, then try again.",
  "agent.failedEmpty": "I couldn't finish an answer in time. Try again, or ask something narrower.",
  "agent.failedError": "Something went wrong while I was answering. Try again in a moment.",
  "proxy.started": "Working on this for {name}. I'll answer here when I'm done.",
  "proxy.waiting": "_The comment on {where} is waiting for {name} to approve it._",
  "proxy.cardTitle": "Post your agent's comment on {where}?",
  "proxy.posted": "Posted on {where}: {url}",
  "proxy.postFailed": "Could not post on {where}. GitHub refused it or is not connected.",
  "autobuild.issue": "Starting on {issues} on my own. I'll post the pull request here when it's ready.",
  "autobuild.report": "This looks like something to fix in the code, so I'm starting on it. I'll post the pull request here when it's ready.",
  "teammate.started": "On it. I'll answer here when I'm done.",
  "teammate.continued": "Picking this up where we left off.",
  "teammate.limit": "I've reached this workspace's monthly spending limit for me. An admin can raise it in Studio → AI teammates.",
  "teammate.notHere": "I'm not set up to work in this channel. An admin can add it in Studio → AI teammates.",
  "teammate.failed": "I couldn't start on this. Check my setup in Studio → AI teammates, then try again.",
  "teammate.budget": "I stopped because I reached this month's spending limit. An admin can raise it in Studio → AI teammates.",
  "teammate.off": "I'm switched off in this workspace. An admin can turn me on in Studio → AI teammates.",
  "teammate.done": "Done.",
  "teammate.stopped": "I stopped before finishing. Mention me again to pick it up.",
  "teammate.busy": "I'm still working on the last request in this thread. Ask again once I've answered.",
  "channel.added": "{who} added {names} to the channel.",
  "channel.left": "{who} left the channel.",
  "channel.removed": "{who} removed {name} from the channel.",
  "channel.agentAdded": "{who} added the agent {name} here. Anyone here can call it.",
  "channel.agentRemoved": "{who} removed the agent {name} from here.",
  "route.selectedByYou": "Selected by you",
  "channel.failed": "Could not make that a decision. Try again.",
  "channel.failedBecause": "Could not make that a decision: {reason}",
  "channel.you": "you",
  "channel.made": "Made this a decision for {who}: {title}",
  "channel.why": "Why: {why}",
  "channel.autoApproved": "Approved automatically by {name}'s rule.",
  "channel.fromMessages": "Make a decision from these messages",
  "channel.agentYourAI": "Your AI",
  "suggest.nudge": "Chase {name} for an answer on “{title}”",
  "suggest.ask": "Ask {name} to sign off on this week’s priorities",
  "suggest.askIn": "Ask {name} to sign off on this week’s plan for #{channel}",
  "suggest.weekly": "Every Monday at 9, summarise last week’s decisions",
  "suggest.weeklyIn": "Every Monday at 9, summarise last week’s decisions in #{channel}",
  "suggest.friday": "Every Friday at 17:00, tell me what is still waiting on others",
  "suggest.followUp": "Remind me tomorrow at 9 to follow up on “{title}”",
  "suggest.tomorrow": "Remind me tomorrow at 9 to review what is waiting on me",
  "suggest.monthly": "On the 1st of every month at 9, summarise last month’s decisions",
  "jam.started": "{name} started a Jam.",
  "jam.ended": "Jam ended · {minutes} min · {people}",
  "jam.notes": "Notes from the Jam · {minutes} min · {people}",
  "jam.recording": "Recording: {url}",
  "jam.noNotes": "The Jam was recorded, but nobody could be heard clearly enough to take notes.",
  "reminder.title": "Reminder: {text}",
  "reminder.savedBy": "Saved from a message by {name}.",
  "reminder.saved": "Saved from a message.",
  "proposal.source": "Automation proposal",
  "proposal.title": "Automate: {what}",
  "proposal.summary": "You asked for this {count} times in the last few weeks. Approve, and your AI will do it {schedule} and bring the result here.",
  "proposal.context": "Asked on {dates}. Decline and this will not be proposed again. You can change or stop the routine any time under Automations.",
  "routine.briefTitle": "Morning brief",
  "routine.briefInstruction": "Brief me for the day: what is waiting on me, what has been stuck for more than two days across the team, and what was decided since yesterday.",
  "schedule.daily": "Every day at {time}",
  "schedule.weekdays": "Weekdays at {time}",
  "schedule.weekly": "Every {day} at {time}",
  "schedule.monthly": "Monthly on day {day} at {time}",
  "schedule.monthEnd": "Last day of the month at {time}",
  "schedule.day0": "Sunday",
  "schedule.day1": "Monday",
  "schedule.day2": "Tuesday",
  "schedule.day3": "Wednesday",
  "schedule.day4": "Thursday",
  "schedule.day5": "Friday",
  "schedule.day6": "Saturday",
  "daily.routineTitle": "Daily report",
  "daily.instruction": "Write my daily report in my own words: what I said and did today, how far each task I was given got, what went well, what to improve, and exactly what I will do tomorrow.",
  "daily.title": "Daily report — {date}",
  "daily.summary": "A draft of your day. Read it, change anything, then post it to {channel}.",
  "daily.done": "What I did today",
  "daily.progress": "Task progress",
  "daily.good": "What went well",
  "daily.improve": "What to improve",
  "daily.tomorrow": "Tomorrow",
  "daily.nothing": "Nothing recorded today.",
  "daily.fillIn": "(add this in your own words)",
  "daily.refineUnavailable": "Your AI is not available right now, so the draft is as it was.",
  "canvas.draftUnavailable": "Your AI is not available right now, or nothing has been said here yet, so the canvas is as it was.",
  "daily.messages": "Wrote {count} messages in {where}",
  "daily.decided": "{title}: {action}",
  "daily.asked": "Asked {name}: {title}",
  "daily.open": "{title} (from {name}) — in progress, {days} days",
  "daily.openToday": "{title} (from {name}) — in progress",
  "daily.commented": "Commented on {title}",
  "daily.planRoutineTitle": "Morning plan",
  "daily.planInstruction": "Write my plan for today in my own words: what I will do today, most important first, where my tasks stand, and what I need help with.",
  "daily.planTitle": "Plan for today — {date}",
  "daily.today": "Today",
  "daily.status": "Task status",
  "daily.help": "Where I need help",
  "daily.waitingOn": "Waiting on {name}: {title}",
};

const JA = {
  "jam.transcript": "文字起こし",
  "invite.joined": "{name}さんがワークスペースに参加しました。ようこそ！",
  "welcome.dm": "{name}さん、{team}へようこそ！はじめに知っておくと便利なこと：\n- 左のチャンネルに、話題ごとのチームの会話があります。\n- *@AI* と書けばAIに何でも質問でき、スレッドで答えます。誰かに決めてほしいときは「決定事項として送信」（✦）で送ってください。\n- *@* とエージェント名を書くと、調べもの・要約・下書きを頼めます。\n- ほかの言語のメッセージは自動であなたの言語に翻訳されます。\nわからないことは、このDMで{owner}さんに聞いてください。",
  "welcome.yourTeam": "チーム",
  "invite.someone": "新しいメンバー",
  "invite.agentJoined": "エージェント「{name}」が参加しました（{by}さんの代わりに動きます）。",
  "agent.noModel": "まだ答えられません。このワークスペースにはAIのモデルが設定されていません。管理者がツールで選べます。",
  "agent.quota": "今日のAIの回答回数を使い切りました。明日か、Proでまた使えます。",
  "agent.failed": "今は答えられませんでした。少し待ってからもう一度試してください。",
  "agent.failedService": "回答できませんでした。AIサービスがリクエストを受け付けませんでした。ツール → AI でワークスペースのAIキーを確認してから、もう一度試してください。",
  "agent.failedEmpty": "時間内に回答をまとめきれませんでした。もう一度試すか、質問を絞ってください。",
  "agent.failedError": "回答中にエラーが起きました。少し待ってからもう一度試してください。",
  "proxy.started": "{name}さんの代わりに取りかかります。終わったらここで返信します。",
  "proxy.waiting": "_{where} へのコメントは{name}さんの承認待ちです。_",
  "proxy.cardTitle": "エージェントのコメントを {where} に投稿しますか？",
  "proxy.posted": "{where} に投稿しました: {url}",
  "proxy.postFailed": "{where} に投稿できませんでした。GitHubに拒否されたか、接続されていません。",
  "autobuild.issue": "{issues} の実装を自動で始めます。プルリクエストができたらここに投稿します。",
  "autobuild.report": "コードの修正が必要そうなので、自動で取りかかります。プルリクエストができたらここに投稿します。",
  "teammate.started": "取りかかります。終わったらここで返信します。",
  "teammate.continued": "続きから取りかかります。",
  "teammate.limit": "このワークスペースで今月使える上限に達しました。管理者が Studio → AIチームメイト で上限を変えられます。",
  "teammate.notHere": "このチャンネルでは作業できる設定になっていません。管理者が Studio → AIチームメイト で追加できます。",
  "teammate.failed": "作業を始められませんでした。Studio → AIチームメイト の設定を確認して、もう一度呼んでください。",
  "teammate.budget": "今月の上限に達したので作業を止めました。管理者が Studio → AIチームメイト で上限を変えられます。",
  "teammate.off": "このワークスペースではオフになっています。管理者が Studio → AIチームメイト でオンにできます。",
  "teammate.done": "完了しました。",
  "teammate.stopped": "途中で止まりました。もう一度呼んでもらえれば続きから進めます。",
  "teammate.busy": "このスレッドの前の依頼にまだ取り組んでいます。返信したあとにもう一度お願いします。",
  "channel.added": "{who}さんが{names}さんをチャンネルに追加しました。",
  "channel.left": "{who}さんがチャンネルを抜けました。",
  "channel.removed": "{who}さんが{name}さんをチャンネルから外しました。",
  "channel.agentAdded": "{who}さんがエージェント {name} を追加しました。ここにいる全員が呼び出せます。",
  "channel.agentRemoved": "{who}さんがエージェント {name} を外しました。",
  "route.selectedByYou": "あなたが選択",
  "channel.failed": "決定カードにできませんでした。もう一度試してください。",
  "channel.failedBecause": "決定カードにできませんでした: {reason}",
  "channel.you": "あなた",
  "channel.made": "{who}への決定カードにしました: {title}",
  "channel.why": "理由: {why}",
  "channel.autoApproved": "{name}さんのルールで自動承認されました。",
  "channel.fromMessages": "これらのメッセージから決定を作って",
  "channel.agentYourAI": "あなたのAI",
  "suggest.nudge": "{name}さんに「{title}」の返事を催促して",
  "suggest.ask": "今週の優先順位を{name}さんに承認してもらって",
  "suggest.askIn": "#{channel}の今週の計画を{name}さんに承認してもらって",
  "suggest.weekly": "毎週月曜9時に先週の決定をまとめて",
  "suggest.weeklyIn": "毎週月曜9時に#{channel}の先週の決定をまとめて",
  "suggest.friday": "毎週金曜17時に、返事待ちのものを教えて",
  "suggest.followUp": "明日9時に「{title}」のフォローを思い出させて",
  "suggest.tomorrow": "明日9時に、自分宛ての決定を確認するよう思い出させて",
  "suggest.monthly": "毎月1日の9時に先月の決定をまとめて",
  "jam.started": "{name}さんがJamを始めました。",
  "jam.ended": "Jamが終了しました · {minutes}分 · {people}",
  "jam.notes": "Jamのメモ · {minutes}分 · {people}",
  "jam.recording": "録音: {url}",
  "jam.noNotes": "Jamを録音しましたが、メモにできるほど声を聞き取れませんでした。",
  "reminder.title": "リマインダー: {text}",
  "reminder.savedBy": "{name}さんのメッセージから保存しました。",
  "reminder.saved": "メッセージから保存しました。",
  "proposal.source": "自動化の提案",
  "proposal.title": "自動化しませんか: {what}",
  "proposal.summary": "この数週間で{count}回依頼しています。承認すると、AIが{schedule}に実行して結果をここに届けます。",
  "proposal.context": "依頼日: {dates}。却下すると二度と提案しません。ルーティンはいつでも「自動化」から変更・停止できます。",
  "routine.briefTitle": "朝のブリーフ",
  "routine.briefInstruction": "今日のブリーフ: 自分待ちの判断、チームで2日以上止まっているもの、昨日から決まったこと。",
  "schedule.daily": "毎日 {time}",
  "schedule.weekdays": "平日 {time}",
  "schedule.weekly": "毎週{day} {time}",
  "schedule.monthly": "毎月{day}日 {time}",
  "schedule.monthEnd": "毎月末 {time}",
  "schedule.day0": "日曜",
  "schedule.day1": "月曜",
  "schedule.day2": "火曜",
  "schedule.day3": "水曜",
  "schedule.day4": "木曜",
  "schedule.day5": "金曜",
  "schedule.day6": "土曜",
  "daily.routineTitle": "日報",
  "daily.instruction": "自分の言葉で日報を書く: 今日の発言とやったこと、指示されたタスクの進捗、良かった点、反省点、明日やることを具体的に。",
  "daily.title": "日報 {date}",
  "daily.summary": "今日の下書きです。確認して、直したいところを直してから {channel} に投稿してください。",
  "daily.done": "今日やったこと",
  "daily.progress": "タスクの進捗",
  "daily.good": "良かった点",
  "daily.improve": "反省点",
  "daily.tomorrow": "明日やること",
  "daily.nothing": "今日の記録はありません。",
  "daily.fillIn": "（自分の言葉で書いてください）",
  "daily.refineUnavailable": "いまは AI を使えないため、下書きはそのままです。",
  "canvas.draftUnavailable": "いまは AI を使えないか、まだ会話がないため、キャンバスはそのままです。",
  "daily.messages": "{where}で{count}件発言",
  "daily.decided": "{title}: {action}",
  "daily.asked": "{name}さんに依頼: {title}",
  "daily.open": "{title}（{name}さんから）— 対応中、{days}日目",
  "daily.openToday": "{title}（{name}さんから）— 対応中",
  "daily.commented": "{title} にコメント",
  "daily.planRoutineTitle": "朝の予定",
  "daily.planInstruction": "自分の言葉で今日の予定を書く: 今日やること（大事な順）、タスクの状況、相談したいこと。",
  "daily.planTitle": "今日の予定 {date}",
  "daily.today": "今日やること",
  "daily.status": "タスクの状況",
  "daily.help": "相談したいこと",
  "daily.waitingOn": "{name}さんの返事待ち: {title}",
};

const ES = {
  "jam.transcript": "Transcripción",
  "invite.joined": "{name} se unió al espacio de trabajo. ¡Salúdale!",
  "welcome.dm": "¡Bienvenido a {team}, {name}! Algunas cosas para empezar:\n- Los canales de la izquierda tienen las conversaciones del equipo, un tema cada uno.\n- Escribe *@AI* para preguntar lo que sea a tu IA; responde en el hilo. Para que alguien decida, envíalo como decisión (✦).\n- Escribe *@* y el nombre de un agente para que investigue, resuma o redacte por ti.\n- Los mensajes en otros idiomas se traducen al tuyo automáticamente.\nCualquier otra cosa, pregúntale a {owner} aquí mismo.",
  "welcome.yourTeam": "tu equipo",
  "invite.someone": "Alguien nuevo",
  "invite.agentJoined": "El agente «{name}» se unió y trabaja para {by}.",
  "agent.noModel": "Aún no puedo responder: este espacio de trabajo no tiene un modelo de IA. Un administrador puede elegir uno en Herramientas.",
  "agent.quota": "Has usado las respuestas de IA de hoy. Mañana, o con Pro, tendrás más.",
  "agent.failed": "No pude responder ahora. Inténtalo de nuevo en un momento.",
  "agent.failedService": "No pude responder: el servicio de IA rechazó la solicitud. Revisa la clave de IA del espacio en Herramientas → IA y vuelve a intentarlo.",
  "agent.failedEmpty": "No pude terminar una respuesta a tiempo. Inténtalo de nuevo o pregunta algo más concreto.",
  "agent.failedError": "Algo falló mientras respondía. Inténtalo de nuevo en un momento.",
  "proxy.started": "Me pongo con esto por {name}. Responderé aquí cuando termine.",
  "proxy.waiting": "_El comentario en {where} espera la aprobación de {name}._",
  "proxy.cardTitle": "¿Publicar el comentario de tu agente en {where}?",
  "proxy.posted": "Publicado en {where}: {url}",
  "proxy.postFailed": "No se pudo publicar en {where}. GitHub lo rechazó o no está conectado.",
  "autobuild.issue": "Empiezo por mi cuenta con {issues}. Publicaré aquí el pull request cuando esté listo.",
  "autobuild.report": "Parece algo que arreglar en el código, así que me pongo con ello. Publicaré aquí el pull request cuando esté listo.",
  "teammate.started": "Me pongo con ello. Responderé aquí cuando termine.",
  "teammate.continued": "Sigo donde lo dejamos.",
  "teammate.limit": "He alcanzado el límite mensual de gasto de este espacio de trabajo. Un administrador puede subirlo en Studio → Compañeros IA.",
  "teammate.notHere": "No estoy configurado para trabajar en este canal. Un administrador puede añadirlo en Studio → Compañeros IA.",
  "teammate.failed": "No pude empezar. Revisa mi configuración en Studio → Compañeros IA e inténtalo de nuevo.",
  "teammate.budget": "Me detuve al alcanzar el límite de gasto de este mes. Un administrador puede subirlo en Studio → Compañeros IA.",
  "teammate.off": "Estoy desactivado en este espacio de trabajo. Un administrador puede activarme en Studio → Compañeros IA.",
  "teammate.done": "Hecho.",
  "teammate.stopped": "Me detuve antes de terminar. Mencióname de nuevo para continuar.",
  "teammate.busy": "Sigo trabajando en la petición anterior de este hilo. Vuelve a pedirlo cuando haya respondido.",
  "channel.added": "{who} añadió a {names} al canal.",
  "channel.left": "{who} salió del canal.",
  "channel.removed": "{who} quitó a {name} del canal.",
  "channel.agentAdded": "{who} añadió el agente {name} aquí. Cualquiera aquí puede llamarlo.",
  "channel.agentRemoved": "{who} quitó el agente {name} de aquí.",
  "route.selectedByYou": "Elegido por ti",
  "channel.failed": "No se pudo convertir en una decisión. Inténtalo de nuevo.",
  "channel.failedBecause": "No se pudo convertir en una decisión: {reason}",
  "channel.you": "ti",
  "channel.made": "Convertido en una decisión para {who}: {title}",
  "channel.why": "Motivo: {why}",
  "channel.autoApproved": "Aprobado automáticamente por la regla de {name}.",
  "channel.fromMessages": "Crea una decisión a partir de estos mensajes",
  "channel.agentYourAI": "Tu IA",
  "suggest.nudge": "Pide a {name} una respuesta sobre «{title}»",
  "suggest.ask": "Pide a {name} que apruebe las prioridades de esta semana",
  "suggest.askIn": "Pide a {name} que apruebe el plan de esta semana de #{channel}",
  "suggest.weekly": "Cada lunes a las 9, resume las decisiones de la semana pasada",
  "suggest.weeklyIn": "Cada lunes a las 9, resume las decisiones de la semana pasada en #{channel}",
  "suggest.friday": "Cada viernes a las 17:00, dime qué sigue esperando respuesta de otros",
  "suggest.followUp": "Recuérdame mañana a las 9 hacer seguimiento de «{title}»",
  "suggest.tomorrow": "Recuérdame mañana a las 9 revisar lo que espera mi decisión",
  "suggest.monthly": "El día 1 de cada mes a las 9, resume las decisiones del mes pasado",
  "jam.started": "{name} inició un Jam.",
  "jam.ended": "Jam terminado · {minutes} min · {people}",
  "jam.notes": "Notas del Jam · {minutes} min · {people}",
  "jam.recording": "Grabación: {url}",
  "jam.noNotes": "El Jam se grabó, pero no se oyó a nadie con claridad suficiente para tomar notas.",
  "reminder.title": "Recordatorio: {text}",
  "reminder.savedBy": "Guardado de un mensaje de {name}.",
  "reminder.saved": "Guardado de un mensaje.",
  "proposal.source": "Propuesta de automatización",
  "proposal.title": "Automatizar: {what}",
  "proposal.summary": "Has pedido esto {count} veces en las últimas semanas. Si lo apruebas, tu IA lo hará {schedule} y traerá el resultado aquí.",
  "proposal.context": "Pedido el {dates}. Si lo rechazas, no se volverá a proponer. Puedes cambiar o detener la rutina cuando quieras en Automatizaciones.",
  "routine.briefTitle": "Resumen matutino",
  "routine.briefInstruction": "Hazme el resumen del día: lo que espera mi decisión, lo que lleva más de dos días atascado en el equipo y lo que se decidió desde ayer.",
  "schedule.daily": "Cada día a las {time}",
  "schedule.weekdays": "Días laborables a las {time}",
  "schedule.weekly": "Cada {day} a las {time}",
  "schedule.monthly": "Cada mes el día {day} a las {time}",
  "schedule.monthEnd": "El último día del mes a las {time}",
  "schedule.day0": "domingo",
  "schedule.day1": "lunes",
  "schedule.day2": "martes",
  "schedule.day3": "miércoles",
  "schedule.day4": "jueves",
  "schedule.day5": "viernes",
  "schedule.day6": "sábado",
  "daily.routineTitle": "Informe diario",
  "daily.instruction": "Escribe mi informe diario con mis propias palabras: lo que dije e hice hoy, cómo avanzó cada tarea que me encargaron, qué salió bien, qué mejorar y qué haré exactamente mañana.",
  "daily.title": "Informe diario — {date}",
  "daily.summary": "Un borrador de tu día. Léelo, cambia lo que quieras y publícalo en {channel}.",
  "daily.done": "Lo que hice hoy",
  "daily.progress": "Avance de las tareas",
  "daily.good": "Lo que salió bien",
  "daily.improve": "Qué mejorar",
  "daily.tomorrow": "Mañana",
  "daily.nothing": "Hoy no hay nada registrado.",
  "daily.fillIn": "(añádelo con tus propias palabras)",
  "daily.refineUnavailable": "Tu IA no está disponible ahora; el borrador sigue igual.",
  "canvas.draftUnavailable": "Tu IA no está disponible ahora o aún no se ha dicho nada aquí; el lienzo sigue igual.",
  "daily.messages": "Escribí {count} mensajes en {where}",
  "daily.decided": "{title}: {action}",
  "daily.asked": "Pedí a {name}: {title}",
  "daily.open": "{title} (de {name}) — en curso, {days} días",
  "daily.openToday": "{title} (de {name}) — en curso",
  "daily.commented": "Comenté en {title}",
  "daily.planRoutineTitle": "Plan de la mañana",
  "daily.planInstruction": "Escribe mi plan de hoy con mis propias palabras: qué haré hoy, lo más importante primero, cómo van mis tareas y en qué necesito ayuda.",
  "daily.planTitle": "Plan para hoy — {date}",
  "daily.today": "Hoy",
  "daily.status": "Estado de las tareas",
  "daily.help": "En qué necesito ayuda",
  "daily.waitingOn": "Esperando a {name}: {title}",
};

const FR = {
  "jam.transcript": "Transcription",
  "invite.joined": "{name} a rejoint l’espace de travail. Dites bonjour !",
  "welcome.dm": "Bienvenue dans {team}, {name} ! Quelques repères pour démarrer :\n- Les canaux à gauche rassemblent les conversations de l’équipe, un sujet chacun.\n- Écrivez *@AI* pour poser n’importe quelle question à votre IA ; elle répond dans le fil. Pour faire décider quelqu’un, envoyez-le comme décision (✦).\n- Écrivez *@* et le nom d’un agent pour qu’il cherche, résume ou rédige pour vous.\n- Les messages dans d’autres langues sont traduits dans la vôtre automatiquement.\nPour tout le reste, demandez à {owner} ici même.",
  "welcome.yourTeam": "votre équipe",
  "invite.someone": "Une nouvelle personne",
  "invite.agentJoined": "L’agent « {name} » a rejoint l’espace et travaille pour {by}.",
  "agent.noModel": "Je ne peux pas encore répondre : cet espace de travail n’a pas de modèle d’IA. Un administrateur peut en choisir un dans Outils.",
  "agent.quota": "Vous avez utilisé les réponses IA du jour. Demain, ou avec Pro, vous en aurez d’autres.",
  "agent.failed": "Je n’ai pas pu répondre pour l’instant. Réessayez dans un moment.",
  "agent.failedService": "Je n’ai pas pu répondre : le service d’IA a refusé la demande. Vérifiez la clé d’IA de l’espace dans Outils → IA, puis réessayez.",
  "agent.failedEmpty": "Je n’ai pas pu terminer une réponse à temps. Réessayez, ou posez une question plus précise.",
  "agent.failedError": "Un problème est survenu pendant ma réponse. Réessayez dans un moment.",
  "proxy.started": "Je m’en occupe pour {name}. Je répondrai ici quand j’aurai fini.",
  "proxy.waiting": "_Le commentaire sur {where} attend l’approbation de {name}._",
  "proxy.cardTitle": "Publier le commentaire de votre agent sur {where} ?",
  "proxy.posted": "Publié sur {where} : {url}",
  "proxy.postFailed": "Impossible de publier sur {where}. GitHub l’a refusé ou n’est pas connecté.",
  "autobuild.issue": "Je commence {issues} de moi-même. Je publierai la pull request ici quand elle sera prête.",
  "autobuild.report": "Cela semble être à corriger dans le code, je m’y mets. Je publierai la pull request ici quand elle sera prête.",
  "teammate.started": "Je m’en occupe. Je répondrai ici quand j’aurai fini.",
  "teammate.continued": "Je reprends là où nous en étions.",
  "teammate.limit": "J’ai atteint la limite de dépenses mensuelle de cet espace de travail. Un administrateur peut l’augmenter dans Studio → Coéquipiers IA.",
  "teammate.notHere": "Je ne suis pas configuré pour travailler dans ce canal. Un administrateur peut l’ajouter dans Studio → Coéquipiers IA.",
  "teammate.failed": "Je n’ai pas pu commencer. Vérifiez ma configuration dans Studio → Coéquipiers IA, puis réessayez.",
  "teammate.budget": "Je me suis arrêté en atteignant la limite de dépenses du mois. Un administrateur peut l’augmenter dans Studio → Coéquipiers IA.",
  "teammate.off": "Je suis désactivé dans cet espace de travail. Un administrateur peut m’activer dans Studio → Coéquipiers IA.",
  "teammate.done": "Terminé.",
  "teammate.stopped": "Je me suis arrêté avant la fin. Mentionnez-moi à nouveau pour reprendre.",
  "teammate.busy": "Je travaille encore sur la demande précédente de ce fil. Redemandez une fois que j’aurai répondu.",
  "channel.added": "{who} a ajouté {names} au canal.",
  "channel.left": "{who} a quitté le canal.",
  "channel.removed": "{who} a retiré {name} du canal.",
  "channel.agentAdded": "{who} a ajouté l’agent {name} ici. Tout le monde ici peut l’appeler.",
  "channel.agentRemoved": "{who} a retiré l’agent {name} d’ici.",
  "route.selectedByYou": "Choisi par vous",
  "channel.failed": "Impossible d'en faire une décision. Réessayez.",
  "channel.failedBecause": "Impossible d'en faire une décision : {reason}",
  "channel.you": "vous",
  "channel.made": "Transformé en décision pour {who} : {title}",
  "channel.why": "Pourquoi : {why}",
  "channel.autoApproved": "Approuvé automatiquement par la règle de {name}.",
  "channel.fromMessages": "Créer une décision à partir de ces messages",
  "channel.agentYourAI": "Votre IA",
  "suggest.nudge": "Relance {name} pour une réponse sur « {title} »",
  "suggest.ask": "Demande à {name} de valider les priorités de la semaine",
  "suggest.askIn": "Demande à {name} de valider le plan de la semaine pour #{channel}",
  "suggest.weekly": "Chaque lundi à 9 h, résume les décisions de la semaine passée",
  "suggest.weeklyIn": "Chaque lundi à 9 h, résume les décisions de la semaine passée dans #{channel}",
  "suggest.friday": "Chaque vendredi à 17 h, dis-moi ce qui attend encore une réponse",
  "suggest.followUp": "Rappelle-moi demain à 9 h de relancer « {title} »",
  "suggest.tomorrow": "Rappelle-moi demain à 9 h de revoir ce qui attend ma décision",
  "suggest.monthly": "Le 1er de chaque mois à 9 h, résume les décisions du mois passé",
  "jam.started": "{name} a lancé un Jam.",
  "jam.ended": "Jam terminé · {minutes} min · {people}",
  "jam.notes": "Notes du Jam · {minutes} min · {people}",
  "jam.recording": "Enregistrement : {url}",
  "jam.noNotes": "Le Jam a été enregistré, mais personne ne s’entendait assez clairement pour prendre des notes.",
  "reminder.title": "Rappel : {text}",
  "reminder.savedBy": "Enregistré depuis un message de {name}.",
  "reminder.saved": "Enregistré depuis un message.",
  "proposal.source": "Proposition d'automatisation",
  "proposal.title": "Automatiser : {what}",
  "proposal.summary": "Vous l'avez demandé {count} fois ces dernières semaines. Approuvez, et votre IA s'en chargera {schedule} et apportera le résultat ici.",
  "proposal.context": "Demandé le {dates}. Refusez et cela ne sera plus proposé. Vous pouvez modifier ou arrêter la routine à tout moment dans Automatisations.",
  "routine.briefTitle": "Point du matin",
  "routine.briefInstruction": "Fais-moi le point de la journée : ce qui attend ma décision, ce qui est bloqué depuis plus de deux jours dans l'équipe, et ce qui a été décidé depuis hier.",
  "schedule.daily": "Tous les jours à {time}",
  "schedule.weekdays": "En semaine à {time}",
  "schedule.weekly": "Chaque {day} à {time}",
  "schedule.monthly": "Chaque mois le {day} à {time}",
  "schedule.monthEnd": "Le dernier jour du mois à {time}",
  "schedule.day0": "dimanche",
  "schedule.day1": "lundi",
  "schedule.day2": "mardi",
  "schedule.day3": "mercredi",
  "schedule.day4": "jeudi",
  "schedule.day5": "vendredi",
  "schedule.day6": "samedi",
  "daily.routineTitle": "Rapport quotidien",
  "daily.instruction": "Rédige mon rapport quotidien avec mes propres mots : ce que j'ai dit et fait aujourd'hui, où en est chaque tâche qu'on m'a confiée, ce qui a bien marché, ce qui est à améliorer et ce que je ferai précisément demain.",
  "daily.title": "Rapport quotidien — {date}",
  "daily.summary": "Un brouillon de votre journée. Relisez-le, modifiez ce que vous voulez, puis publiez-le dans {channel}.",
  "daily.done": "Ce que j'ai fait aujourd'hui",
  "daily.progress": "Avancement des tâches",
  "daily.good": "Ce qui a bien marché",
  "daily.improve": "À améliorer",
  "daily.tomorrow": "Demain",
  "daily.nothing": "Rien d'enregistré aujourd'hui.",
  "daily.fillIn": "(à compléter avec vos propres mots)",
  "daily.refineUnavailable": "Votre IA n’est pas disponible pour l’instant ; le brouillon reste tel quel.",
  "canvas.draftUnavailable": "Votre IA n’est pas disponible, ou rien n’a encore été dit ici ; le canevas reste tel quel.",
  "daily.messages": "{count} messages écrits dans {where}",
  "daily.decided": "{title} : {action}",
  "daily.asked": "Demandé à {name} : {title}",
  "daily.open": "{title} (de {name}) — en cours, {days} jours",
  "daily.openToday": "{title} (de {name}) — en cours",
  "daily.commented": "Commentaire sur {title}",
  "daily.planRoutineTitle": "Plan du matin",
  "daily.planInstruction": "Rédige mon plan du jour avec mes propres mots : ce que je ferai aujourd'hui, le plus important d'abord, où en sont mes tâches et sur quoi j'ai besoin d'aide.",
  "daily.planTitle": "Plan du jour — {date}",
  "daily.today": "Aujourd'hui",
  "daily.status": "État des tâches",
  "daily.help": "Où j'ai besoin d'aide",
  "daily.waitingOn": "En attente de {name} : {title}",
};

const DE = {
  "jam.transcript": "Transkript",
  "invite.joined": "{name} ist dem Workspace beigetreten. Sag hallo!",
  "welcome.dm": "Willkommen bei {team}, {name}! Ein paar Dinge für den Anfang:\n- Die Kanäle links enthalten die Gespräche des Teams, je ein Thema.\n- Schreib *@AI*, um deiner KI etwas zu fragen; sie antwortet im Thread. Soll jemand entscheiden, sende es als Entscheidung (✦).\n- Schreib *@* und den Namen eines Agenten, damit er recherchiert, zusammenfasst oder entwirft.\n- Nachrichten in anderen Sprachen werden automatisch in deine übersetzt.\nAlles andere frag {owner} direkt hier.",
  "welcome.yourTeam": "dein Team",
  "invite.someone": "Jemand Neues",
  "invite.agentJoined": "Der Agent „{name}“ ist beigetreten und arbeitet für {by}.",
  "agent.noModel": "Ich kann noch nicht antworten: Dieser Workspace hat kein KI-Modell. Ein Admin kann eines unter Tools wählen.",
  "agent.quota": "Du hast die KI-Antworten für heute aufgebraucht. Morgen oder mit Pro gibt es mehr.",
  "agent.failed": "Ich konnte gerade nicht antworten. Versuch es gleich noch einmal.",
  "agent.failedService": "Ich konnte nicht antworten: Der KI-Dienst hat die Anfrage abgelehnt. Prüfe den KI-Schlüssel des Workspace unter Werkzeuge → KI und versuch es dann erneut.",
  "agent.failedEmpty": "Ich konnte die Antwort nicht rechtzeitig fertigstellen. Versuch es erneut oder frag etwas Engeres.",
  "agent.failedError": "Beim Antworten ist etwas schiefgegangen. Versuch es gleich noch einmal.",
  "proxy.started": "Ich kümmere mich für {name} darum und antworte hier, wenn ich fertig bin.",
  "proxy.waiting": "_Der Kommentar zu {where} wartet auf die Freigabe von {name}._",
  "proxy.cardTitle": "Kommentar deines Agenten auf {where} veröffentlichen?",
  "proxy.posted": "Auf {where} veröffentlicht: {url}",
  "proxy.postFailed": "Konnte nicht auf {where} veröffentlichen. GitHub hat abgelehnt oder ist nicht verbunden.",
  "autobuild.issue": "Ich fange selbstständig mit {issues} an und poste den Pull Request hier, sobald er fertig ist.",
  "autobuild.report": "Das sieht nach etwas aus, das im Code zu beheben ist – ich fange damit an und poste den Pull Request hier, sobald er fertig ist.",
  "teammate.started": "Ich kümmere mich darum und antworte hier, wenn ich fertig bin.",
  "teammate.continued": "Ich mache da weiter, wo wir aufgehört haben.",
  "teammate.limit": "Ich habe das monatliche Ausgabenlimit dieses Workspaces erreicht. Ein Admin kann es unter Studio → KI-Teammitglieder erhöhen.",
  "teammate.notHere": "Ich bin für diesen Channel nicht eingerichtet. Ein Admin kann ihn unter Studio → KI-Teammitglieder hinzufügen.",
  "teammate.failed": "Ich konnte nicht anfangen. Prüf meine Einrichtung unter Studio → KI-Teammitglieder und versuch es noch einmal.",
  "teammate.budget": "Ich habe angehalten, weil das Ausgabenlimit für diesen Monat erreicht ist. Ein Admin kann es unter Studio → KI-Teammitglieder erhöhen.",
  "teammate.off": "Ich bin in diesem Workspace ausgeschaltet. Ein Admin kann mich unter Studio → KI-Teammitglieder einschalten.",
  "teammate.done": "Erledigt.",
  "teammate.stopped": "Ich habe angehalten, bevor ich fertig war. Erwähne mich noch einmal, dann mache ich weiter.",
  "teammate.busy": "Ich arbeite noch an der vorigen Anfrage in diesem Thread. Frag noch einmal, sobald ich geantwortet habe.",
  "channel.added": "{who} hat {names} zum Kanal hinzugefügt.",
  "channel.left": "{who} hat den Kanal verlassen.",
  "channel.removed": "{who} hat {name} aus dem Kanal entfernt.",
  "channel.agentAdded": "{who} hat den Agenten {name} hinzugefügt. Alle hier können ihn aufrufen.",
  "channel.agentRemoved": "{who} hat den Agenten {name} entfernt.",
  "route.selectedByYou": "Von dir ausgewählt",
  "channel.failed": "Daraus konnte keine Entscheidung werden. Versuch es noch einmal.",
  "channel.failedBecause": "Daraus konnte keine Entscheidung werden: {reason}",
  "channel.you": "dich",
  "channel.made": "Als Entscheidung an {who} weitergegeben: {title}",
  "channel.why": "Warum: {why}",
  "channel.autoApproved": "Automatisch freigegeben durch die Regel von {name}.",
  "channel.fromMessages": "Mach aus diesen Nachrichten eine Entscheidung",
  "channel.agentYourAI": "Deine KI",
  "suggest.nudge": "Hake bei {name} wegen „{title}“ nach",
  "suggest.ask": "Lass {name} die Prioritäten dieser Woche freigeben",
  "suggest.askIn": "Lass {name} den Wochenplan für #{channel} freigeben",
  "suggest.weekly": "Fasse jeden Montag um 9 die Entscheidungen der letzten Woche zusammen",
  "suggest.weeklyIn": "Fasse jeden Montag um 9 die Entscheidungen der letzten Woche in #{channel} zusammen",
  "suggest.friday": "Sag mir jeden Freitag um 17 Uhr, was noch auf andere wartet",
  "suggest.followUp": "Erinnere mich morgen um 9, bei „{title}“ nachzuhaken",
  "suggest.tomorrow": "Erinnere mich morgen um 9, zu prüfen, was auf meine Entscheidung wartet",
  "suggest.monthly": "Fasse am 1. jedes Monats um 9 die Entscheidungen des letzten Monats zusammen",
  "jam.started": "{name} hat einen Jam gestartet.",
  "jam.ended": "Jam beendet · {minutes} Min. · {people}",
  "jam.notes": "Notizen aus dem Jam · {minutes} Min. · {people}",
  "jam.recording": "Aufnahme: {url}",
  "jam.noNotes": "Der Jam wurde aufgenommen, aber niemand war deutlich genug zu hören, um Notizen zu machen.",
  "reminder.title": "Erinnerung: {text}",
  "reminder.savedBy": "Aus einer Nachricht von {name} gespeichert.",
  "reminder.saved": "Aus einer Nachricht gespeichert.",
  "proposal.source": "Automatisierungsvorschlag",
  "proposal.title": "Automatisieren: {what}",
  "proposal.summary": "Du hast das in den letzten Wochen {count}-mal angefragt. Gib es frei, und deine KI erledigt es {schedule} und bringt das Ergebnis hierher.",
  "proposal.context": "Angefragt am {dates}. Lehnst du ab, wird es nicht wieder vorgeschlagen. Unter Automatisierungen kannst du die Routine jederzeit ändern oder stoppen.",
  "routine.briefTitle": "Morgen-Briefing",
  "routine.briefInstruction": "Brief mich für den Tag: was auf meine Entscheidung wartet, was im Team seit mehr als zwei Tagen feststeckt und was seit gestern entschieden wurde.",
  "schedule.daily": "Jeden Tag um {time}",
  "schedule.weekdays": "Werktags um {time}",
  "schedule.weekly": "Jeden {day} um {time}",
  "schedule.monthly": "Monatlich am {day}. um {time}",
  "schedule.monthEnd": "Am letzten Tag des Monats um {time}",
  "schedule.day0": "Sonntag",
  "schedule.day1": "Montag",
  "schedule.day2": "Dienstag",
  "schedule.day3": "Mittwoch",
  "schedule.day4": "Donnerstag",
  "schedule.day5": "Freitag",
  "schedule.day6": "Samstag",
  "daily.routineTitle": "Tagesbericht",
  "daily.instruction": "Schreib meinen Tagesbericht in meinen eigenen Worten: was ich heute gesagt und getan habe, wie weit jede Aufgabe ist, die ich bekommen habe, was gut lief, was ich besser machen kann und was ich morgen konkret tue.",
  "daily.title": "Tagesbericht — {date}",
  "daily.summary": "Ein Entwurf deines Tages. Lies ihn, ändere, was du willst, und poste ihn dann in {channel}.",
  "daily.done": "Was ich heute gemacht habe",
  "daily.progress": "Stand der Aufgaben",
  "daily.good": "Was gut lief",
  "daily.improve": "Was ich besser machen kann",
  "daily.tomorrow": "Morgen",
  "daily.nothing": "Heute nichts erfasst.",
  "daily.fillIn": "(in deinen eigenen Worten ergänzen)",
  "daily.refineUnavailable": "Deine KI ist gerade nicht verfügbar; der Entwurf bleibt, wie er war.",
  "canvas.draftUnavailable": "Deine KI ist gerade nicht verfügbar oder hier wurde noch nichts gesagt; das Canvas bleibt, wie es war.",
  "daily.messages": "{count} Nachrichten in {where} geschrieben",
  "daily.decided": "{title}: {action}",
  "daily.asked": "{name} gebeten: {title}",
  "daily.open": "{title} (von {name}) — in Arbeit, seit {days} Tagen",
  "daily.openToday": "{title} (von {name}) — in Arbeit",
  "daily.commented": "{title} kommentiert",
  "daily.planRoutineTitle": "Morgenplan",
  "daily.planInstruction": "Schreib meinen Plan für heute in meinen eigenen Worten: was ich heute tue, das Wichtigste zuerst, wie meine Aufgaben stehen und wobei ich Hilfe brauche.",
  "daily.planTitle": "Plan für heute — {date}",
  "daily.today": "Heute",
  "daily.status": "Stand der Aufgaben",
  "daily.help": "Wobei ich Hilfe brauche",
  "daily.waitingOn": "Warte auf {name}: {title}",
};

export const serverText = registerCatalog("server", { en: EN, ja: JA, es: ES, fr: FR, de: DE });
