import { registerCatalog } from "./copy.js";

// What the Worker says in its own voice outside a notification: the reply in
// a channel when a message becomes a decision, a reminder card, a proposal to
// automate, a routine's name and its schedule read aloud. Written by hand in
// the languages below; any other is learned by copy.js on first use.

const EN = {
  "channel.failed": "Could not make that a decision. Try again.",
  "channel.failedBecause": "Could not make that a decision: {reason}",
  "channel.you": "you",
  "channel.made": "Made this a decision for {who}: {title}",
  "channel.why": "Why: {why}",
  "channel.autoApproved": "Approved automatically by {name}'s rule.",
  "channel.fromMessages": "Make a decision from these messages",
  "channel.agentYourAI": "Your AI",
  "jam.started": "{name} started a Jam.",
  "jam.ended": "Jam ended · {minutes} min · {people}",
  "jam.notes": "Notes from the Jam · {minutes} min · {people}",
  "jam.recording": "Recording: {url}",
  "jam.noNotes": "The Jam was recorded, but nobody could be heard clearly enough to take notes.",
  "reminder.title": "Reminder: {text}",
  "reminder.savedBy": "Saved from a message by {name}.",
  "reminder.saved": "Saved from a message.",
  "proposal.source": "Automation proposal",
  "proposal.title": "Automate: {what}",
  "proposal.summary": "You asked for this {count} times in the last few weeks. Approve, and your AI will do it {schedule} and bring the result here.",
  "proposal.context": "Asked on {dates}. Decline and this will not be proposed again. You can change or stop the routine any time under Automations.",
  "routine.briefTitle": "Morning brief",
  "routine.briefInstruction": "Brief me for the day: what is waiting on me, what has been stuck for more than two days across the team, and what was decided since yesterday.",
  "schedule.daily": "Every day at {time}",
  "schedule.weekdays": "Weekdays at {time}",
  "schedule.weekly": "Every {day} at {time}",
  "schedule.monthly": "Monthly on day {day} at {time}",
  "schedule.monthEnd": "Last day of the month at {time}",
  "schedule.day0": "Sunday",
  "schedule.day1": "Monday",
  "schedule.day2": "Tuesday",
  "schedule.day3": "Wednesday",
  "schedule.day4": "Thursday",
  "schedule.day5": "Friday",
  "schedule.day6": "Saturday",
  "daily.routineTitle": "Daily report",
  "daily.instruction": "Write my daily report in my own words: what I said and did today, how far each task I was given got, what went well, what to improve, and exactly what I will do tomorrow.",
  "daily.title": "Daily report — {date}",
  "daily.summary": "A draft of your day. Read it, change anything, then post it to {channel}.",
  "daily.done": "What I did today",
  "daily.progress": "Task progress",
  "daily.good": "What went well",
  "daily.improve": "What to improve",
  "daily.tomorrow": "Tomorrow",
  "daily.nothing": "Nothing recorded today.",
  "daily.fillIn": "(add this in your own words)",
  "daily.messages": "Wrote {count} messages in {where}",
  "daily.decided": "{title}: {action}",
  "daily.asked": "Asked {name}: {title}",
  "daily.open": "{title} (from {name}) — in progress, {days} days",
  "daily.openToday": "{title} (from {name}) — in progress",
  "daily.commented": "Commented on {title}",
  "daily.planRoutineTitle": "Morning plan",
  "daily.planInstruction": "Write my plan for today in my own words: what I will do today, most important first, where my tasks stand, and what I need help with.",
  "daily.planTitle": "Plan for today — {date}",
  "daily.today": "Today",
  "daily.status": "Task status",
  "daily.help": "Where I need help",
  "daily.waitingOn": "Waiting on {name}: {title}",
};

const JA = {
  "channel.failed": "決定カードにできませんでした。もう一度試してください。",
  "channel.failedBecause": "決定カードにできませんでした: {reason}",
  "channel.you": "あなた",
  "channel.made": "{who}への決定カードにしました: {title}",
  "channel.why": "理由: {why}",
  "channel.autoApproved": "{name}さんのルールで自動承認されました。",
  "channel.fromMessages": "これらのメッセージから決定を作って",
  "channel.agentYourAI": "あなたのAI",
  "jam.started": "{name}さんがJamを始めました。",
  "jam.ended": "Jamが終了しました · {minutes}分 · {people}",
  "jam.notes": "Jamのメモ · {minutes}分 · {people}",
  "jam.recording": "録音: {url}",
  "jam.noNotes": "Jamを録音しましたが、メモにできるほど声を聞き取れませんでした。",
  "reminder.title": "リマインダー: {text}",
  "reminder.savedBy": "{name}さんのメッセージから保存しました。",
  "reminder.saved": "メッセージから保存しました。",
  "proposal.source": "自動化の提案",
  "proposal.title": "自動化しませんか: {what}",
  "proposal.summary": "この数週間で{count}回依頼しています。承認すると、AIが{schedule}に実行して結果をここに届けます。",
  "proposal.context": "依頼日: {dates}。却下すると二度と提案しません。ルーティンはいつでも「自動化」から変更・停止できます。",
  "routine.briefTitle": "朝のブリーフ",
  "routine.briefInstruction": "今日のブリーフ: 自分待ちの判断、チームで2日以上止まっているもの、昨日から決まったこと。",
  "schedule.daily": "毎日 {time}",
  "schedule.weekdays": "平日 {time}",
  "schedule.weekly": "毎週{day} {time}",
  "schedule.monthly": "毎月{day}日 {time}",
  "schedule.monthEnd": "毎月末 {time}",
  "schedule.day0": "日曜",
  "schedule.day1": "月曜",
  "schedule.day2": "火曜",
  "schedule.day3": "水曜",
  "schedule.day4": "木曜",
  "schedule.day5": "金曜",
  "schedule.day6": "土曜",
  "daily.routineTitle": "日報",
  "daily.instruction": "自分の言葉で日報を書く: 今日の発言とやったこと、指示されたタスクの進捗、良かった点、反省点、明日やることを具体的に。",
  "daily.title": "日報 {date}",
  "daily.summary": "今日の下書きです。確認して、直したいところを直してから {channel} に投稿してください。",
  "daily.done": "今日やったこと",
  "daily.progress": "タスクの進捗",
  "daily.good": "良かった点",
  "daily.improve": "反省点",
  "daily.tomorrow": "明日やること",
  "daily.nothing": "今日の記録はありません。",
  "daily.fillIn": "（自分の言葉で書いてください）",
  "daily.messages": "{where}で{count}件発言",
  "daily.decided": "{title}: {action}",
  "daily.asked": "{name}さんに依頼: {title}",
  "daily.open": "{title}（{name}さんから）— 対応中、{days}日目",
  "daily.openToday": "{title}（{name}さんから）— 対応中",
  "daily.commented": "{title} にコメント",
  "daily.planRoutineTitle": "朝の予定",
  "daily.planInstruction": "自分の言葉で今日の予定を書く: 今日やること（大事な順）、タスクの状況、相談したいこと。",
  "daily.planTitle": "今日の予定 {date}",
  "daily.today": "今日やること",
  "daily.status": "タスクの状況",
  "daily.help": "相談したいこと",
  "daily.waitingOn": "{name}さんの返事待ち: {title}",
};

const ES = {
  "channel.failed": "No se pudo convertir en una decisión. Inténtalo de nuevo.",
  "channel.failedBecause": "No se pudo convertir en una decisión: {reason}",
  "channel.you": "ti",
  "channel.made": "Convertido en una decisión para {who}: {title}",
  "channel.why": "Motivo: {why}",
  "channel.autoApproved": "Aprobado automáticamente por la regla de {name}.",
  "channel.fromMessages": "Crea una decisión a partir de estos mensajes",
  "channel.agentYourAI": "Tu IA",
  "jam.started": "{name} inició un Jam.",
  "jam.ended": "Jam terminado · {minutes} min · {people}",
  "jam.notes": "Notas del Jam · {minutes} min · {people}",
  "jam.recording": "Grabación: {url}",
  "jam.noNotes": "El Jam se grabó, pero no se oyó a nadie con claridad suficiente para tomar notas.",
  "reminder.title": "Recordatorio: {text}",
  "reminder.savedBy": "Guardado de un mensaje de {name}.",
  "reminder.saved": "Guardado de un mensaje.",
  "proposal.source": "Propuesta de automatización",
  "proposal.title": "Automatizar: {what}",
  "proposal.summary": "Has pedido esto {count} veces en las últimas semanas. Si lo apruebas, tu IA lo hará {schedule} y traerá el resultado aquí.",
  "proposal.context": "Pedido el {dates}. Si lo rechazas, no se volverá a proponer. Puedes cambiar o detener la rutina cuando quieras en Automatizaciones.",
  "routine.briefTitle": "Resumen matutino",
  "routine.briefInstruction": "Hazme el resumen del día: lo que espera mi decisión, lo que lleva más de dos días atascado en el equipo y lo que se decidió desde ayer.",
  "schedule.daily": "Cada día a las {time}",
  "schedule.weekdays": "Días laborables a las {time}",
  "schedule.weekly": "Cada {day} a las {time}",
  "schedule.monthly": "Cada mes el día {day} a las {time}",
  "schedule.monthEnd": "El último día del mes a las {time}",
  "schedule.day0": "domingo",
  "schedule.day1": "lunes",
  "schedule.day2": "martes",
  "schedule.day3": "miércoles",
  "schedule.day4": "jueves",
  "schedule.day5": "viernes",
  "schedule.day6": "sábado",
  "daily.routineTitle": "Informe diario",
  "daily.instruction": "Escribe mi informe diario con mis propias palabras: lo que dije e hice hoy, cómo avanzó cada tarea que me encargaron, qué salió bien, qué mejorar y qué haré exactamente mañana.",
  "daily.title": "Informe diario — {date}",
  "daily.summary": "Un borrador de tu día. Léelo, cambia lo que quieras y publícalo en {channel}.",
  "daily.done": "Lo que hice hoy",
  "daily.progress": "Avance de las tareas",
  "daily.good": "Lo que salió bien",
  "daily.improve": "Qué mejorar",
  "daily.tomorrow": "Mañana",
  "daily.nothing": "Hoy no hay nada registrado.",
  "daily.fillIn": "(añádelo con tus propias palabras)",
  "daily.messages": "Escribí {count} mensajes en {where}",
  "daily.decided": "{title}: {action}",
  "daily.asked": "Pedí a {name}: {title}",
  "daily.open": "{title} (de {name}) — en curso, {days} días",
  "daily.openToday": "{title} (de {name}) — en curso",
  "daily.commented": "Comenté en {title}",
  "daily.planRoutineTitle": "Plan de la mañana",
  "daily.planInstruction": "Escribe mi plan de hoy con mis propias palabras: qué haré hoy, lo más importante primero, cómo van mis tareas y en qué necesito ayuda.",
  "daily.planTitle": "Plan para hoy — {date}",
  "daily.today": "Hoy",
  "daily.status": "Estado de las tareas",
  "daily.help": "En qué necesito ayuda",
  "daily.waitingOn": "Esperando a {name}: {title}",
};

const FR = {
  "channel.failed": "Impossible d'en faire une décision. Réessayez.",
  "channel.failedBecause": "Impossible d'en faire une décision : {reason}",
  "channel.you": "vous",
  "channel.made": "Transformé en décision pour {who} : {title}",
  "channel.why": "Pourquoi : {why}",
  "channel.autoApproved": "Approuvé automatiquement par la règle de {name}.",
  "channel.fromMessages": "Créer une décision à partir de ces messages",
  "channel.agentYourAI": "Votre IA",
  "jam.started": "{name} a lancé un Jam.",
  "jam.ended": "Jam terminé · {minutes} min · {people}",
  "jam.notes": "Notes du Jam · {minutes} min · {people}",
  "jam.recording": "Enregistrement : {url}",
  "jam.noNotes": "Le Jam a été enregistré, mais personne ne s’entendait assez clairement pour prendre des notes.",
  "reminder.title": "Rappel : {text}",
  "reminder.savedBy": "Enregistré depuis un message de {name}.",
  "reminder.saved": "Enregistré depuis un message.",
  "proposal.source": "Proposition d'automatisation",
  "proposal.title": "Automatiser : {what}",
  "proposal.summary": "Vous l'avez demandé {count} fois ces dernières semaines. Approuvez, et votre IA s'en chargera {schedule} et apportera le résultat ici.",
  "proposal.context": "Demandé le {dates}. Refusez et cela ne sera plus proposé. Vous pouvez modifier ou arrêter la routine à tout moment dans Automatisations.",
  "routine.briefTitle": "Point du matin",
  "routine.briefInstruction": "Fais-moi le point de la journée : ce qui attend ma décision, ce qui est bloqué depuis plus de deux jours dans l'équipe, et ce qui a été décidé depuis hier.",
  "schedule.daily": "Tous les jours à {time}",
  "schedule.weekdays": "En semaine à {time}",
  "schedule.weekly": "Chaque {day} à {time}",
  "schedule.monthly": "Chaque mois le {day} à {time}",
  "schedule.monthEnd": "Le dernier jour du mois à {time}",
  "schedule.day0": "dimanche",
  "schedule.day1": "lundi",
  "schedule.day2": "mardi",
  "schedule.day3": "mercredi",
  "schedule.day4": "jeudi",
  "schedule.day5": "vendredi",
  "schedule.day6": "samedi",
  "daily.routineTitle": "Rapport quotidien",
  "daily.instruction": "Rédige mon rapport quotidien avec mes propres mots : ce que j'ai dit et fait aujourd'hui, où en est chaque tâche qu'on m'a confiée, ce qui a bien marché, ce qui est à améliorer et ce que je ferai précisément demain.",
  "daily.title": "Rapport quotidien — {date}",
  "daily.summary": "Un brouillon de votre journée. Relisez-le, modifiez ce que vous voulez, puis publiez-le dans {channel}.",
  "daily.done": "Ce que j'ai fait aujourd'hui",
  "daily.progress": "Avancement des tâches",
  "daily.good": "Ce qui a bien marché",
  "daily.improve": "À améliorer",
  "daily.tomorrow": "Demain",
  "daily.nothing": "Rien d'enregistré aujourd'hui.",
  "daily.fillIn": "(à compléter avec vos propres mots)",
  "daily.messages": "{count} messages écrits dans {where}",
  "daily.decided": "{title} : {action}",
  "daily.asked": "Demandé à {name} : {title}",
  "daily.open": "{title} (de {name}) — en cours, {days} jours",
  "daily.openToday": "{title} (de {name}) — en cours",
  "daily.commented": "Commentaire sur {title}",
  "daily.planRoutineTitle": "Plan du matin",
  "daily.planInstruction": "Rédige mon plan du jour avec mes propres mots : ce que je ferai aujourd'hui, le plus important d'abord, où en sont mes tâches et sur quoi j'ai besoin d'aide.",
  "daily.planTitle": "Plan du jour — {date}",
  "daily.today": "Aujourd'hui",
  "daily.status": "État des tâches",
  "daily.help": "Où j'ai besoin d'aide",
  "daily.waitingOn": "En attente de {name} : {title}",
};

const DE = {
  "channel.failed": "Daraus konnte keine Entscheidung werden. Versuch es noch einmal.",
  "channel.failedBecause": "Daraus konnte keine Entscheidung werden: {reason}",
  "channel.you": "dich",
  "channel.made": "Als Entscheidung an {who} weitergegeben: {title}",
  "channel.why": "Warum: {why}",
  "channel.autoApproved": "Automatisch freigegeben durch die Regel von {name}.",
  "channel.fromMessages": "Mach aus diesen Nachrichten eine Entscheidung",
  "channel.agentYourAI": "Deine KI",
  "jam.started": "{name} hat einen Jam gestartet.",
  "jam.ended": "Jam beendet · {minutes} Min. · {people}",
  "jam.notes": "Notizen aus dem Jam · {minutes} Min. · {people}",
  "jam.recording": "Aufnahme: {url}",
  "jam.noNotes": "Der Jam wurde aufgenommen, aber niemand war deutlich genug zu hören, um Notizen zu machen.",
  "reminder.title": "Erinnerung: {text}",
  "reminder.savedBy": "Aus einer Nachricht von {name} gespeichert.",
  "reminder.saved": "Aus einer Nachricht gespeichert.",
  "proposal.source": "Automatisierungsvorschlag",
  "proposal.title": "Automatisieren: {what}",
  "proposal.summary": "Du hast das in den letzten Wochen {count}-mal angefragt. Gib es frei, und deine KI erledigt es {schedule} und bringt das Ergebnis hierher.",
  "proposal.context": "Angefragt am {dates}. Lehnst du ab, wird es nicht wieder vorgeschlagen. Unter Automatisierungen kannst du die Routine jederzeit ändern oder stoppen.",
  "routine.briefTitle": "Morgen-Briefing",
  "routine.briefInstruction": "Brief mich für den Tag: was auf meine Entscheidung wartet, was im Team seit mehr als zwei Tagen feststeckt und was seit gestern entschieden wurde.",
  "schedule.daily": "Jeden Tag um {time}",
  "schedule.weekdays": "Werktags um {time}",
  "schedule.weekly": "Jeden {day} um {time}",
  "schedule.monthly": "Monatlich am {day}. um {time}",
  "schedule.monthEnd": "Am letzten Tag des Monats um {time}",
  "schedule.day0": "Sonntag",
  "schedule.day1": "Montag",
  "schedule.day2": "Dienstag",
  "schedule.day3": "Mittwoch",
  "schedule.day4": "Donnerstag",
  "schedule.day5": "Freitag",
  "schedule.day6": "Samstag",
  "daily.routineTitle": "Tagesbericht",
  "daily.instruction": "Schreib meinen Tagesbericht in meinen eigenen Worten: was ich heute gesagt und getan habe, wie weit jede Aufgabe ist, die ich bekommen habe, was gut lief, was ich besser machen kann und was ich morgen konkret tue.",
  "daily.title": "Tagesbericht — {date}",
  "daily.summary": "Ein Entwurf deines Tages. Lies ihn, ändere, was du willst, und poste ihn dann in {channel}.",
  "daily.done": "Was ich heute gemacht habe",
  "daily.progress": "Stand der Aufgaben",
  "daily.good": "Was gut lief",
  "daily.improve": "Was ich besser machen kann",
  "daily.tomorrow": "Morgen",
  "daily.nothing": "Heute nichts erfasst.",
  "daily.fillIn": "(in deinen eigenen Worten ergänzen)",
  "daily.messages": "{count} Nachrichten in {where} geschrieben",
  "daily.decided": "{title}: {action}",
  "daily.asked": "{name} gebeten: {title}",
  "daily.open": "{title} (von {name}) — in Arbeit, seit {days} Tagen",
  "daily.openToday": "{title} (von {name}) — in Arbeit",
  "daily.commented": "{title} kommentiert",
  "daily.planRoutineTitle": "Morgenplan",
  "daily.planInstruction": "Schreib meinen Plan für heute in meinen eigenen Worten: was ich heute tue, das Wichtigste zuerst, wie meine Aufgaben stehen und wobei ich Hilfe brauche.",
  "daily.planTitle": "Plan für heute — {date}",
  "daily.today": "Heute",
  "daily.status": "Stand der Aufgaben",
  "daily.help": "Wobei ich Hilfe brauche",
  "daily.waitingOn": "Warte auf {name}: {title}",
};

export const serverText = registerCatalog("server", { en: EN, ja: JA, es: ES, fr: FR, de: DE });
