import { registerCatalog } from "./copy.js";

// What the Worker says in its own voice outside a notification: the reply in
// a channel when a message becomes a decision, a reminder card, a proposal to
// automate, a routine's name and its schedule read aloud. Written by hand in
// the languages below; any other is learned by copy.js on first use.

const EN = {
  "channel.failed": "Could not make that a decision. Try again.",
  "channel.failedBecause": "Could not make that a decision: {reason}",
  "channel.you": "you",
  "channel.made": "Made this a decision for {who}: {title}",
  "channel.why": "Why: {why}",
  "channel.autoApproved": "Approved automatically by {name}'s rule.",
  "channel.fromMessages": "Make a decision from these messages",
  "reminder.title": "Reminder: {text}",
  "reminder.savedBy": "Saved from a message by {name}.",
  "reminder.saved": "Saved from a message.",
  "proposal.source": "Automation proposal",
  "proposal.title": "Automate: {what}",
  "proposal.summary": "You asked for this {count} times in the last few weeks. Approve, and your AI will do it {schedule} and bring the result here.",
  "proposal.context": "Asked on {dates}. Decline and this will not be proposed again. You can change or stop the routine any time under Automations.",
  "routine.briefTitle": "Morning brief",
  "routine.briefInstruction": "Brief me for the day: what is waiting on me, what has been stuck for more than two days across the team, and what was decided since yesterday.",
  "schedule.daily": "Every day at {time}",
  "schedule.weekdays": "Weekdays at {time}",
  "schedule.weekly": "Every {day} at {time}",
  "schedule.monthly": "Monthly on day {day} at {time}",
  "schedule.monthEnd": "Last day of the month at {time}",
  "schedule.day0": "Sunday",
  "schedule.day1": "Monday",
  "schedule.day2": "Tuesday",
  "schedule.day3": "Wednesday",
  "schedule.day4": "Thursday",
  "schedule.day5": "Friday",
  "schedule.day6": "Saturday",
};

const JA = {
  "channel.failed": "決定カードにできませんでした。もう一度試してください。",
  "channel.failedBecause": "決定カードにできませんでした: {reason}",
  "channel.you": "あなた",
  "channel.made": "{who}への決定カードにしました: {title}",
  "channel.why": "理由: {why}",
  "channel.autoApproved": "{name}さんのルールで自動承認されました。",
  "channel.fromMessages": "これらのメッセージから決定を作って",
  "reminder.title": "リマインダー: {text}",
  "reminder.savedBy": "{name}さんのメッセージから保存しました。",
  "reminder.saved": "メッセージから保存しました。",
  "proposal.source": "自動化の提案",
  "proposal.title": "自動化しませんか: {what}",
  "proposal.summary": "この数週間で{count}回依頼しています。承認すると、AIが{schedule}に実行して結果をここに届けます。",
  "proposal.context": "依頼日: {dates}。却下すると二度と提案しません。ルーティンはいつでも「自動化」から変更・停止できます。",
  "routine.briefTitle": "朝のブリーフ",
  "routine.briefInstruction": "今日のブリーフ: 自分待ちの判断、チームで2日以上止まっているもの、昨日から決まったこと。",
  "schedule.daily": "毎日 {time}",
  "schedule.weekdays": "平日 {time}",
  "schedule.weekly": "毎週{day} {time}",
  "schedule.monthly": "毎月{day}日 {time}",
  "schedule.monthEnd": "毎月末 {time}",
  "schedule.day0": "日曜",
  "schedule.day1": "月曜",
  "schedule.day2": "火曜",
  "schedule.day3": "水曜",
  "schedule.day4": "木曜",
  "schedule.day5": "金曜",
  "schedule.day6": "土曜",
};

const ES = {
  "channel.failed": "No se pudo convertir en una decisión. Inténtalo de nuevo.",
  "channel.failedBecause": "No se pudo convertir en una decisión: {reason}",
  "channel.you": "ti",
  "channel.made": "Convertido en una decisión para {who}: {title}",
  "channel.why": "Motivo: {why}",
  "channel.autoApproved": "Aprobado automáticamente por la regla de {name}.",
  "channel.fromMessages": "Crea una decisión a partir de estos mensajes",
  "reminder.title": "Recordatorio: {text}",
  "reminder.savedBy": "Guardado de un mensaje de {name}.",
  "reminder.saved": "Guardado de un mensaje.",
  "proposal.source": "Propuesta de automatización",
  "proposal.title": "Automatizar: {what}",
  "proposal.summary": "Has pedido esto {count} veces en las últimas semanas. Si lo apruebas, tu IA lo hará {schedule} y traerá el resultado aquí.",
  "proposal.context": "Pedido el {dates}. Si lo rechazas, no se volverá a proponer. Puedes cambiar o detener la rutina cuando quieras en Automatizaciones.",
  "routine.briefTitle": "Resumen matutino",
  "routine.briefInstruction": "Hazme el resumen del día: lo que espera mi decisión, lo que lleva más de dos días atascado en el equipo y lo que se decidió desde ayer.",
  "schedule.daily": "Cada día a las {time}",
  "schedule.weekdays": "Días laborables a las {time}",
  "schedule.weekly": "Cada {day} a las {time}",
  "schedule.monthly": "Cada mes el día {day} a las {time}",
  "schedule.monthEnd": "El último día del mes a las {time}",
  "schedule.day0": "domingo",
  "schedule.day1": "lunes",
  "schedule.day2": "martes",
  "schedule.day3": "miércoles",
  "schedule.day4": "jueves",
  "schedule.day5": "viernes",
  "schedule.day6": "sábado",
};

const FR = {
  "channel.failed": "Impossible d'en faire une décision. Réessayez.",
  "channel.failedBecause": "Impossible d'en faire une décision : {reason}",
  "channel.you": "vous",
  "channel.made": "Transformé en décision pour {who} : {title}",
  "channel.why": "Pourquoi : {why}",
  "channel.autoApproved": "Approuvé automatiquement par la règle de {name}.",
  "channel.fromMessages": "Créer une décision à partir de ces messages",
  "reminder.title": "Rappel : {text}",
  "reminder.savedBy": "Enregistré depuis un message de {name}.",
  "reminder.saved": "Enregistré depuis un message.",
  "proposal.source": "Proposition d'automatisation",
  "proposal.title": "Automatiser : {what}",
  "proposal.summary": "Vous l'avez demandé {count} fois ces dernières semaines. Approuvez, et votre IA s'en chargera {schedule} et apportera le résultat ici.",
  "proposal.context": "Demandé le {dates}. Refusez et cela ne sera plus proposé. Vous pouvez modifier ou arrêter la routine à tout moment dans Automatisations.",
  "routine.briefTitle": "Point du matin",
  "routine.briefInstruction": "Fais-moi le point de la journée : ce qui attend ma décision, ce qui est bloqué depuis plus de deux jours dans l'équipe, et ce qui a été décidé depuis hier.",
  "schedule.daily": "Tous les jours à {time}",
  "schedule.weekdays": "En semaine à {time}",
  "schedule.weekly": "Chaque {day} à {time}",
  "schedule.monthly": "Chaque mois le {day} à {time}",
  "schedule.monthEnd": "Le dernier jour du mois à {time}",
  "schedule.day0": "dimanche",
  "schedule.day1": "lundi",
  "schedule.day2": "mardi",
  "schedule.day3": "mercredi",
  "schedule.day4": "jeudi",
  "schedule.day5": "vendredi",
  "schedule.day6": "samedi",
};

const DE = {
  "channel.failed": "Daraus konnte keine Entscheidung werden. Versuch es noch einmal.",
  "channel.failedBecause": "Daraus konnte keine Entscheidung werden: {reason}",
  "channel.you": "dich",
  "channel.made": "Als Entscheidung an {who} weitergegeben: {title}",
  "channel.why": "Warum: {why}",
  "channel.autoApproved": "Automatisch freigegeben durch die Regel von {name}.",
  "channel.fromMessages": "Mach aus diesen Nachrichten eine Entscheidung",
  "reminder.title": "Erinnerung: {text}",
  "reminder.savedBy": "Aus einer Nachricht von {name} gespeichert.",
  "reminder.saved": "Aus einer Nachricht gespeichert.",
  "proposal.source": "Automatisierungsvorschlag",
  "proposal.title": "Automatisieren: {what}",
  "proposal.summary": "Du hast das in den letzten Wochen {count}-mal angefragt. Gib es frei, und deine KI erledigt es {schedule} und bringt das Ergebnis hierher.",
  "proposal.context": "Angefragt am {dates}. Lehnst du ab, wird es nicht wieder vorgeschlagen. Unter Automatisierungen kannst du die Routine jederzeit ändern oder stoppen.",
  "routine.briefTitle": "Morgen-Briefing",
  "routine.briefInstruction": "Brief mich für den Tag: was auf meine Entscheidung wartet, was im Team seit mehr als zwei Tagen feststeckt und was seit gestern entschieden wurde.",
  "schedule.daily": "Jeden Tag um {time}",
  "schedule.weekdays": "Werktags um {time}",
  "schedule.weekly": "Jeden {day} um {time}",
  "schedule.monthly": "Monatlich am {day}. um {time}",
  "schedule.monthEnd": "Am letzten Tag des Monats um {time}",
  "schedule.day0": "Sonntag",
  "schedule.day1": "Montag",
  "schedule.day2": "Dienstag",
  "schedule.day3": "Mittwoch",
  "schedule.day4": "Donnerstag",
  "schedule.day5": "Freitag",
  "schedule.day6": "Samstag",
};

export const serverText = registerCatalog("server", { en: EN, ja: JA, es: ES, fr: FR, de: DE });
