import React, { useEffect, useRef, useState } from 'react'
import { ArrowUpRight, Bell, Check, Copy, LogOut, Plug, RefreshCw, RotateCcw, UserRound, Users } from 'lucide-react'
import type { Member } from './Workbench'
import { readResponse } from '../utils/api'
import { getLocale, setLocale, SUPPORTED } from '../utils/locale'
import './WorkspaceForms.css'

interface Props { members: Member[]; membersError?: string; userId: string; displayName: string; onLogout: () => void; onRefresh: () => void; onSwitchOrg?: (orgId: string) => void; httpBase?: string; orgId?: string; sessionToken?: string; sample?: boolean; onReset?: () => void; onLocaleChange?: () => void }
interface Profile { name?: string; email?: string; emailEditable?: boolean; locale?: string; notifyEmail?: boolean }
interface Connector { id: string; label: string; status: string }
export function WorkspaceSettings({ members, membersError, userId, displayName, onLogout, onRefresh, onSwitchOrg, httpBase, orgId, sessionToken, sample, onReset, onLocaleChange }: Props) {
  const [profile, setProfile] = useState<Profile | null>(null), [email, setEmail] = useState(''), [locale, setPreferredLocale] = useState(getLocale())
  const [connectors, setConnectors] = useState<Connector[]>([]), [connectionsState, setConnectionsState] = useState<'loading' | 'ready' | 'unavailable' | 'error'>('loading')
  const [busy, setBusy] = useState(''), [error, setError] = useState(''), [message, setMessage] = useState('')
  const [invite, setInvite] = useState(''), [joinCode, setJoinCode] = useState('')
  const epoch = useRef(0)
  const auth = { 'content-type': 'application/json', 'x-session-token': sessionToken || '' }
  useEffect(() => {
    if (sample) return
    const controller = new AbortController(); const current = ++epoch.current
    fetch(`${httpBase}/me`, { headers: auth, signal: controller.signal }).then(readResponse).then((data) => { if (epoch.current === current) { setProfile(data); setEmail(data.email || ''); setPreferredLocale(data.locale || getLocale()) } }).catch(() => { if (!controller.signal.aborted) setError('Account settings could not be loaded. Refresh to try again.') })
    fetch(`${httpBase}/connectors`, { headers: auth, signal: controller.signal }).then(async (response) => { if (response.status === 503) { if (epoch.current === current) setConnectionsState('unavailable'); return }; const data = await readResponse(response); if (epoch.current === current) { setConnectors(data.connectors || []); setConnectionsState('ready') } }).catch(() => { if (!controller.signal.aborted) setConnectionsState('error') })
    return () => { epoch.current++; controller.abort() }
  }, [sample, httpBase, sessionToken])
  const run = async (name: string, work: () => Promise<void>) => { if (busy) return; const current = epoch.current; setBusy(name); setError(''); setMessage(''); try { await work() } catch (e) { if (epoch.current === current) setError(e instanceof Error ? e.message : 'The change could not be saved.') } finally { if (epoch.current === current) setBusy('') } }
  const request = async (path: string, body?: unknown, method = 'POST') => readResponse(await fetch(`${httpBase}${path}`, { method, headers: auth, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) }))
  const saveProfile = async () => { const current = epoch.current; const data = await request('/me', { locale, ...(profile?.emailEditable ? { email } : {}) }, 'PUT'); if (epoch.current !== current) return; setProfile((p) => ({ ...p, ...data })); setLocale(locale); onLocaleChange?.(); setMessage('Account preferences saved.') }
  return <div className="workspace-page"><div className="workspace-heading"><div><h1>{sample ? 'Sample workspace' : 'Workspace'}</h1><p>{sample ? 'Try the workflow with a sample team. Changes stay local.' : 'Your team, connections, and account preferences.'}</p></div><div>{sample ? <button onClick={onReset}><RotateCcw size={15} />Reset demo</button> : <button onClick={onRefresh}><RefreshCw size={15} />Refresh</button>}</div></div>{error && <div className="form-error" role="alert">{error}</div>}{message && <div className="settings-message" role="status">{message}</div>}
    <section className="settings-section"><header><h2><Users size={18} />Team <span className="wb-demo-badge">{members.length}</span></h2><p>{sample ? 'These teammates and requests are examples.' : 'Choose these teammates as recipients when you create a request.'}</p></header>{membersError && <div className="settings-empty">{membersError}</div>}{members.map((member) => <div className="settings-row" key={member.id}><span className="wb-avatar">{member.name.slice(0, 1)}</span><div><strong>{member.name}{member.id === userId ? ' (you)' : ''}</strong><small>{member.role}</small></div><span>{member.id === userId ? 'You' : 'Member'}</span></div>)}{!sample && <div className="settings-body"><p>Invite someone with a code. Share it yourself; no invitation email is sent.</p><button disabled={!!busy} onClick={() => run('invite', async () => { const current = epoch.current; const data = await request('/invites/create', { orgId, role: 'member' }); if (current === epoch.current) setInvite(data.code) })}>{busy === 'invite' ? 'Creating invite…' : 'Create invite code'}</button>{invite && <div className="settings-invite"><code>{invite}</code><button onClick={() => navigator.clipboard.writeText(invite).then(() => setMessage('Invite code copied.')).catch(() => setError('Select the code and copy it manually.'))}><Copy size={14} />Copy</button></div>}</div>}</section>
    <section className="settings-section"><header><h2><Plug size={18} />Connections</h2><p>Bring requests from the tools your team uses.</p></header>{sample ? <div className="settings-empty"><strong>No tools are connected in the demo.</strong>Sample requests are stored only in this page. Sign in to connect your own tools.</div> : connectionsState === 'loading' ? <div className="settings-empty">Loading connections…</div> : connectionsState !== 'ready' ? <div className="settings-empty"><strong>{connectionsState === 'unavailable' ? 'Connections are not set up yet.' : 'Connections could not be loaded.'}</strong>{connectionsState === 'unavailable' ? 'Your administrator needs to enable tool connections. You can still send requests directly to teammates.' : 'Refresh this workspace to try again.'}</div> : connectors.map((connector) => connector.id === 'notion' && connector.status === 'active' ? <NotionConnection key={connector.id} httpBase={httpBase!} sessionToken={sessionToken!} orgId={orgId!} /> : <div className="settings-row" key={connector.id}><span className="wb-avatar"><Plug size={16} /></span><div><strong>{connector.label}</strong><small>{connector.status === 'active' ? 'Connected' : 'Not connected'}</small></div><button disabled={!!busy} onClick={() => run(connector.id, async () => { const current = epoch.current; if (connector.status === 'active') { const result = await request(`/connectors/${encodeURIComponent(connector.id)}/sync`, { orgId }); if (current === epoch.current) setMessage(`${connector.label} synced. ${result.created || 0} new requests.`) } else { const result = await request(`/connectors/${encodeURIComponent(connector.id)}/connect`); if (current !== epoch.current) return; const url = new URL(result.redirectUrl); if (url.protocol !== 'https:') throw new Error('A secure connection link could not be opened.'); window.open(url.href, '_blank', 'noopener,noreferrer'); setMessage('Complete the connection in the new tab, then refresh this workspace.') } })}>{busy === connector.id ? 'Working…' : connector.status === 'active' ? 'Sync' : 'Connect'}{connector.status === 'active' ? <RefreshCw size={13} /> : <ArrowUpRight size={13} />}</button></div>)}</section>
    <section className="settings-section"><header><h2><UserRound size={18} />Account & notifications</h2><p>{sample ? 'Alex Morgan · Demo account' : displayName}</p></header><div className="settings-body">{sample ? <p>There is no signed-in account, email delivery, or push notification in this sample workspace.</p> : profile ? <form onSubmit={(e) => { e.preventDefault(); run('profile', saveProfile) }}><div className="form-columns"><label className="settings-field">Card & notification language<select value={locale} onChange={(e) => setPreferredLocale(e.target.value)} disabled={!!busy}>{SUPPORTED.map((code) => <option key={code} value={code}>{code === 'ja' ? '日本語' : 'English'}</option>)}</select></label><label className="settings-field">Email address<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} disabled={!profile.emailEditable || !!busy} /></label></div><p>The interface is currently in English. This preference controls translated request content and notifications.</p>{profile.email && <label className="settings-toggle"><input type="checkbox" checked={!!profile.notifyEmail} disabled={!!busy} onChange={(e) => { const next = e.target.checked; run('notifications', async () => { const current = epoch.current; await request('/me', { notifyEmail: next }, 'PUT'); if (current === epoch.current) { setProfile((p) => ({ ...p, notifyEmail: next })); setMessage('Notification preference saved.') } }) }} /><Bell size={15} />Email me when no device can be reached</label>}<button type="submit" disabled={!!busy} className="primary-button"><Check size={14} />{busy === 'profile' ? 'Saving…' : 'Save preferences'}</button></form> : <p>Loading account preferences…</p>}</div></section>
    {!sample && <section className="settings-section"><header><h2>Join another workspace</h2><p>Enter an invite code. After joining, this session opens that workspace.</p></header><form className="settings-body settings-inline" onSubmit={(e) => { e.preventDefault(); run('join', async () => { const current = epoch.current; const data = await request('/invites/accept', { code: joinCode.trim() }); if (current === epoch.current && data.orgId) onSwitchOrg?.(data.orgId) }) }}><label className="settings-field">Invite code<input value={joinCode} onChange={(e) => setJoinCode(e.target.value)} required autoComplete="off" /></label><button disabled={!!busy || !joinCode.trim()}>{busy === 'join' ? 'Joining…' : 'Join workspace'}</button></form></section>}
    <footer className="settings-footer"><span>{sample ? 'Reset or exit at any time. Demo changes are not saved after a reload.' : 'Your workspace updates live while you work.'}</span><button onClick={onLogout}><LogOut size={15} />{sample ? 'Exit demo' : 'Sign out'}</button></footer>
  </div>
}


function NotionConnection({ httpBase, sessionToken, orgId }: { httpBase: string; sessionToken: string; orgId: string }) {
  const [databases, setDatabases] = useState<Array<{ id: string; title: string }>>([])
  const [selected, setSelected] = useState(''), [saved, setSaved] = useState(''), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState('')
  const live = useRef(true)
  const headers = { 'content-type': 'application/json', 'x-session-token': sessionToken }
  useEffect(() => {
    live.current = true; const abort = new AbortController()
    Promise.all([fetch(`${httpBase}/connectors/notion/databases`, { headers, signal: abort.signal }).then(readResponse), fetch(`${httpBase}/connectors/notion/config`, { headers, signal: abort.signal }).then(readResponse)]).then(([list, config]) => { if (!abort.signal.aborted) { setDatabases(list.databases || []); setSelected(config.databaseId || ''); setSaved(config.databaseId || '') } }).catch(() => { if (!abort.signal.aborted) setError('Notion databases could not be loaded. Refresh Workspace to try again.') }).finally(() => { if (!abort.signal.aborted) setLoading(false) })
    return () => { live.current = false; abort.abort() }
  }, [httpBase, sessionToken, orgId])
  const action = async (sync: boolean) => {
    if (busy) return; setBusy(true); setError(''); setMessage('')
    try {
      const data = await readResponse(await fetch(`${httpBase}/connectors/notion/${sync ? 'sync' : 'config'}`, { method: sync ? 'POST' : 'PUT', headers, body: JSON.stringify(sync ? { orgId } : { databaseId: selected }) }))
      if (!live.current) return
      if (sync) setMessage(`Notion synced. ${data.created || 0} new requests.`)
      else { setSaved(selected); setMessage('Notion database saved. You can now sync requests.') }
    } catch (e) { if (live.current) setError(e instanceof Error ? e.message : 'Notion could not be updated.') }
    finally { if (live.current) setBusy(false) }
  }
  return <div className="settings-body"><p><strong>Notion · Connected</strong></p><p>Choose the database to import requests from before syncing.</p>{loading ? <p>Loading databases…</p> : <div className="settings-inline"><label className="settings-field">Notion database<select aria-label="Notion database" value={selected} onChange={(e) => setSelected(e.target.value)} disabled={busy || !databases.length}><option value="">Choose a database</option>{databases.map((d) => <option key={d.id} value={d.id}>{d.title}</option>)}</select></label><button onClick={() => action(false)} disabled={busy || !selected || selected === saved}>Save database</button><button onClick={() => action(true)} disabled={busy || !saved || selected !== saved || !databases.some((d) => d.id === saved)}><RefreshCw size={14} />{busy ? 'Working…' : 'Sync'}</button></div>}{!loading && !databases.length && !error && <p>No shared databases found. Grant Notion access to a database, then refresh Workspace.</p>}{error && <div className="form-error" role="alert">{error}</div>}{message && <div className="settings-message" role="status">{message}</div>}</div>
}
