// Real browser workflows against disposable local services. Never use production.
import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
const require = createRequire(import.meta.url)
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const base = process.env.WEB_QA_URL || 'http://127.0.0.1:3000'
const api = process.env.WORKER_QA_URL || 'http://127.0.0.1:8787'
const local = (url) => ['127.0.0.1', 'localhost', '[::1]'].includes(new URL(url).hostname)
assert(local(base) && local(api), 'Browser QA requires local disposable web and Worker services')
const isWorker = (url) => local(url) && new URL(url).port === new URL(api).port
const workerResponse = (response, path) => isWorker(response.url()) && new URL(response.url()).pathname === path
const health = await (await fetch(`${api}/health`)).json()
assert.equal(health.ok, true)
for (const key of ['githubOAuth', 'aiRouting', 'push', 'webPush', 'email']) assert.equal(health[key], false, `QA requires ${key} disabled`)
const output = process.env.WEB_QA_OUTPUT || '/tmp/honmaruai-web-qa/screenshots'
await mkdir(output, { recursive: true })
const browser = await chromium.launch({ headless: true })
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1, colorScheme: 'light', locale: 'en-US' })
const page = await context.newPage(), errors = [], checks = []
page.setDefaultTimeout(15000)
let demoActive = false, demoBackendRequests = 0, holdDeltas = false, releaseRoute
const delayedDeltas = []
await context.route('**/*', (route) => {
  const url = new URL(route.request().url())
  if (['http:', 'https:'].includes(url.protocol) && !local(url)) { errors.push(`Blocked non-local request: ${url.origin}`); return route.abort('blockedbyclient') }
  if (demoActive && isWorker(url)) demoBackendRequests++
  return route.continue()
})
// Do not let an accidentally misconfigured app open an external relay either.
await context.routeWebSocket(/.*/, (socket) => {
  const url = new URL(socket.url())
  if (!local(url)) { errors.push(`Blocked non-local socket: ${url.origin}`); socket.close(); return }
  const isRelay = isWorker(url)
  if (demoActive && isRelay) demoBackendRequests++
  const server = socket.connectToServer()
  server.onMessage((message) => {
    let event
    try { event = JSON.parse(String(message)) } catch { /* Vite messages pass through. */ }
    if (isRelay && holdDeltas && event?.type === 'STATE_DELTA') delayedDeltas.push(() => socket.send(message))
    else socket.send(message)
  })
})
page.on('pageerror', (error) => errors.push(error.message))
const passed = (name) => { checks.push(name); console.log(`PASS ${name}`) }
const waitFor = async (condition, message) => { const end = Date.now() + 15000; while (Date.now() < end) { if (await condition()) return; await new Promise((resolve) => setTimeout(resolve, 75)) } throw new Error(message) }
const shot = (name) => page.screenshot({ path: `${output}/${name}.png` })
const cards = () => page.locator('.feed .card')
const home = () => page.locator('.tabbar [data-tab="feed"]').click()
const profile = () => page.locator('.tabbar [data-tab="you"]').click()
const compose = () => page.locator('.tabbar [data-tab="compose"]').click()
const classic = () => page.getByRole('tab', { name: 'Classic', exact: true }).click()
const section = (name) => page.locator('.cl-section').filter({ has: page.getByRole('heading', { name: new RegExp(`^${name}`) }) })
const cardPage = (title) => page.locator('.feed .page').filter({ has: page.locator('h1').filter({ hasText: title }) })
const revealCard = async (title) => { const item = cardPage(title); await item.scrollIntoViewIfNeeded(); await waitFor(async () => await item.getAttribute('aria-hidden') !== 'true', `Request did not become active: ${title}`); return item }
const closeDialog = () => page.getByRole('dialog').getByRole('button', { name: 'Close', exact: true }).click()
const confirmUndo = async () => { const dialog = page.getByRole('dialog', { name: 'Undo response?', exact: true }); await dialog.getByRole('button', { name: 'Undo response', exact: true }).click() }
const reply = async (title, text) => {
  const item = await revealCard(title)
  await item.getByRole('button', { name: 'Add to request', exact: true }).click()
  await item.getByRole('button', { name: 'Respond to sender', exact: true }).click()
  await item.getByLabel('Ask your AI about this decision', { exact: true }).fill(text)
  await item.getByRole('button', { name: 'Send', exact: true }).click()
}

try {
  await page.goto(base, { waitUntil: 'networkidle' })
  await page.getByRole('button', { name: 'I already have an account', exact: true }).click()
  await shot('auth-desktop')
  demoActive = true
  await page.getByRole('button', { name: 'Try a local sample workspace', exact: true }).click()
  await waitFor(async () => await cards().count() === 5, 'Sample feed did not load five requests')
  await shot('demo-feed-desktop')
  await classic()
  assert.equal(await section('Waiting on you').locator('.cl-open').count(), 5)
  assert.equal(await section('Sent by you').locator('.cl-open').count(), 1)
  assert.equal(await section('Decided').locator('.cl-open').count(), 1)
  await section('Sent by you').locator('.cl-open').click()
  await page.getByTestId('request-detail').getByText('Confirm the launch-day monitoring checklist', { exact: true }).waitFor()
  await closeDialog()
  passed('Sample Cards and Classic share five incoming, one sent, and one completed request')
  await home()
  await (await revealCard('Check the new teammate onboarding flow')).getByRole('button', { name: 'Complete task', exact: true }).click()
  await waitFor(async () => await cards().count() === 4, 'Sample completion did not change local state')
  await page.locator('.decision-feedback').getByRole('button', { name: 'Undo', exact: true }).click()
  await confirmUndo()
  await waitFor(async () => await cards().count() === 5, 'Sample undo did not restore the task')
  await reply('Approve the autumn launch homepage', 'The launch copy is ready. Please include the final checklist.')
  await waitFor(async () => await cards().count() === 4, 'Sample reply did not complete the request')
  passed('Sample task completion, confirmed Undo, and response change only local state')
  await page.setViewportSize({ width: 390, height: 844 })
  await compose()
  const draft = page.getByRole('dialog', { name: 'Tell your AI', exact: true })
  await draft.getByLabel('Recipient', { exact: true }).selectOption('sample:maya')
  await draft.getByLabel('What needs your attention?', { exact: true }).fill('Review the updated customer interview plan before Thursday.')
  await draft.getByRole('button', { name: 'Review request', exact: true }).click()
  await draft.getByLabel('Subject', { exact: true }).fill('Review the customer interview plan')
  await shot('demo-compose-mobile')
  assert.equal(await cards().count(), 4, 'Preview sent prematurely')
  await draft.getByRole('button', { name: 'Create sample request', exact: true }).click()
  await waitFor(async () => await page.getByRole('dialog').count() === 0, 'Sample composer did not close')
  await classic()
  assert.equal(await section('Sent by you').locator('.cl-open').count(), 2)
  await profile()
  await page.locator('.figma-profile-account > summary').click()
  await page.getByRole('button', { name: 'Reset demo', exact: true }).click()
  await home()
  assert.equal(await cards().count(), 5)
  await shot('demo-feed-mobile')
  const geometry = await page.evaluate(() => ({ overflow: document.documentElement.scrollWidth > innerWidth, navTop: document.querySelector('.tabbar').getBoundingClientRect().top, askBottom: document.querySelector('.feed .ask-bar').getBoundingClientRect().bottom }))
  assert.equal(geometry.overflow, false); assert(geometry.askBottom <= geometry.navTop + 1, 'Composer overlaps persistent navigation')
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' })
  await shot('demo-feed-mobile-dark')
  await profile()
  await page.getByRole('button', { name: 'Exit demo', exact: true }).last().click()
  assert.equal(demoBackendRequests, 0, 'Sample workspace contacted the Worker')
  demoActive = false
  passed('Mobile sample preview/create/reset/exit, unobscured navigation, and zero backend requests or sockets')

  await page.setViewportSize({ width: 1440, height: 1000 }); await page.emulateMedia({ colorScheme: 'light' })
  await page.getByRole('button', { name: 'Create an account', exact: true }).click()
  await page.getByRole('button', { name: 'Use a password instead', exact: true }).click()
  const email = `web-figma-${Date.now()}@example.invalid`, password = 'Local-QA-only-2026!'
  await page.getByLabel('Your name', { exact: true }).fill('Release Review')
  await page.getByLabel('Email', { exact: true }).fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  const signup = page.waitForResponse((response) => workerResponse(response, '/auth/signup') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  const signupResponse = await signup
  assert.equal(signupResponse.status(), 200)
  const identity = await signupResponse.json()
  const authHeaders = { 'x-session-token': identity.token }
  const record = async () => { const response = await context.request.get(`${api}/record?orgId=${encodeURIComponent(identity.orgId)}`, { headers: authHeaders }); assert.equal(response.status(), 200); return response.json() }
  await page.getByRole('group', { name: 'Role', exact: true }).getByRole('button', { name: 'Engineer', exact: true }).click()
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('group', { name: 'Language', exact: true }).getByRole('button', { name: 'English', exact: true }).click()
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await home()
  await page.locator('.feed[aria-busy="false"]').waitFor()
  await page.getByRole('heading', { name: 'All clear', exact: true }).waitFor()
  await page.locator('.dot.on').waitFor({ state: 'attached' })
  const onboarded = await context.request.get(`${api}/me?orgId=${encodeURIComponent(identity.orgId)}`, { headers: authHeaders })
  const onboardedProfile = await onboarded.json()
  assert.equal(onboardedProfile.role, 'engineer'); assert.equal(onboardedProfile.locale, 'en')
  await shot('inbox-empty-desktop')
  passed('Real password signup, onboarding title/language, current membership, and authenticated socket join')

  await compose()
  const composer = page.getByRole('dialog', { name: 'Tell your AI', exact: true })
  await composer.getByLabel('Recipient', { exact: true }).selectOption(identity.login)
  await composer.getByLabel('What needs your attention?', { exact: true }).fill('Please approve the launch brief by Friday. Budget: $2,400. The owner is Release Review.')
  const routed = page.waitForResponse((response) => workerResponse(response, '/ai/route'))
  await composer.getByRole('button', { name: 'Review request', exact: true }).click()
  const routeResponse = await routed, routing = await routeResponse.json()
  assert.equal(routeResponse.status(), 200); assert.equal(routing.recipientUserID, identity.login); assert.equal(routing.routedBy, 'fallback')
  await composer.getByLabel('Subject', { exact: true }).fill('Approve the launch brief')
  await composer.getByLabel('Request type', { exact: true }).selectOption('approval')
  await composer.getByLabel('Background', { exact: true }).fill('The brief has passed editorial review. Final sign-off is needed before production.')
  assert.equal(await cards().count(), 0)
  assert(!JSON.stringify(await record()).includes('Approve the launch brief'), 'Preview was persisted before Send')
  assert.equal(await page.locator('.feed[inert]').count(), 1, 'Background feed was not isolated behind the composer')
  await shot('composer-preview-desktop')
  passed('Actual recipient, honest fallback drafting, editable preview, no premature save, and modal isolation')
  await composer.getByRole('button', { name: 'Send request', exact: true }).click()
  await waitFor(async () => await page.getByRole('dialog').count() === 0 && await cards().count() === 1, 'Server-confirmed delivery did not finish')
  assert(JSON.stringify(await record()).includes('Approve the launch brief'))
  await shot('inbox-decision-desktop')
  holdDeltas = true
  await cardPage('Approve the launch brief').getByRole('button', { name: 'Approve', exact: true }).click()
  await waitFor(async () => delayedDeltas.length > 0, 'Relay did not publish the saved response')
  assert.equal(await cards().count(), 1, 'The UI claimed a response before receiving server state')
  await page.locator('.decision-feedback').getByText('Saving response…', { exact: true }).waitFor()
  holdDeltas = false; delayedDeltas.splice(0).forEach((release) => release())
  await page.locator('.decision-feedback').getByText('Response saved.', { exact: true }).waitFor()
  await waitFor(async () => await cards().count() === 0, 'Approval did not update incoming state')
  await classic()
  await section('Decided').locator('.cl-open').click()
  await page.getByTestId('request-detail').getByText('Approved', { exact: false }).waitFor()
  await page.getByTestId('request-detail').getByRole('button', { name: 'Undo', exact: true }).click()
  await confirmUndo()
  await page.locator('.decision-feedback').getByText('Response undone. The request is waiting again.', { exact: true }).waitFor()
  await home(); assert.equal(await cards().count(), 1)
  passed('Persisted delivery and approval, delayed confirmation does not claim success, Classic detail and server-confirmed Undo')

  await page.setViewportSize({ width: 390, height: 844 })
  await reply('Approve the launch brief', 'Reviewed. Please include the final checklist.')
  await page.locator('.decision-feedback').getByText('Response saved.', { exact: true }).waitFor()
  await profile()
  await page.locator('.figma-profile').getByRole('button', { name: 'History', exact: true }).click()
  await page.locator('.hist-group .row').filter({ hasText: 'Approve the launch brief' }).click()
  await page.getByTestId('request-detail').getByText('Reviewed. Please include the final checklist.', { exact: true }).waitFor()
  await shot('completed-detail-mobile')
  await page.reload({ waitUntil: 'networkidle' })
  await page.locator('.dot.on').waitFor({ state: 'attached' })
  await classic()
  await section('Decided').locator('.cl-open').click()
  await page.getByTestId('request-detail').getByText('Reviewed. Please include the final checklist.', { exact: true }).waitFor()
  passed('Real mobile reply, History, and completed request survive reload')
  await closeDialog()
  await profile()
  const profileScreen = page.locator('.figma-profile')
  await profileScreen.getByRole('heading', { name: 'Release Review', exact: true }).waitFor()
  await profileScreen.getByLabel('Language', { exact: true }).selectOption('ja')
  await profileScreen.getByLabel('言語', { exact: true }).waitFor()
  const me = await context.request.get(`${api}/me`, { headers: authHeaders })
  assert.equal((await me.json()).locale, 'ja')
  await shot('profile-mobile-japanese')
  assert.equal(await page.locator('.classic[inert]').count(), 1)
  await profileScreen.getByLabel('言語', { exact: true }).selectOption('en')
  await profileScreen.getByLabel('Language', { exact: true }).waitFor()
  await profileScreen.getByText('Account', { exact: true }).click()
  await profileScreen.getByLabel('Role', { exact: true }).selectOption('designer')
  await waitFor(async () => (await (await context.request.get(`${api}/me?orgId=${encodeURIComponent(identity.orgId)}`, { headers: authHeaders })).json()).role === 'designer', 'Profile title did not persist')
  passed('Profile real identity, Japanese language persistence, descriptive role update, and isolated background')
  await profileScreen.getByRole('button', { name: 'Sign out', exact: true }).click()
  await page.getByRole('button', { name: 'I already have an account', exact: true }).click()
  await page.getByRole('button', { name: 'Use a password instead', exact: true }).click()
  await page.getByLabel('Email', { exact: true }).fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.locator('.dot.on').waitFor({ state: 'attached' })
  await classic(); assert.equal(await section('Decided').locator('.cl-open').count(), 1)
  passed('Sign-out and password re-login restore the actual workspace and saved decision')

  let routeStarted = false
  const gate = new Promise((resolve) => { releaseRoute = resolve })
  await page.route('**/ai/route', async (route) => { const response = await route.fetch(); routeStarted = true; await gate; await route.fulfill({ response }).catch(() => {}) })
  await compose()
  await composer.getByLabel('Recipient', { exact: true }).selectOption(identity.login)
  await composer.getByLabel('What needs your attention?', { exact: true }).fill('Please approve this intentionally delayed local request.')
  await composer.getByRole('button', { name: 'Review request', exact: true }).click()
  await waitFor(async () => routeStarted, 'Delayed preparation never started')
  await page.keyboard.press('Escape'); releaseRoute()
  await waitFor(async () => await page.getByRole('dialog').count() === 0, 'Closed composer was reopened by delayed drafting')
  assert.equal(await section('Sent by you').locator('.cl-open').count(), 1)
  assert(!JSON.stringify(await record()).includes('intentionally delayed'))
  await page.unroute('**/ai/route')
  passed('Closing pending preparation cancels the stale preview without creating another request')

  // Keep the connector regression: local fixtures never contact Notion itself.
  let notionDatabase = null, notionSyncs = 0
  const json = (body) => ({ contentType: 'application/json', body: JSON.stringify(body) })
  await page.route('**/connectors', (route) => route.fulfill(json({ connectors: [{ id: 'notion', label: 'Notion', status: 'active' }] })))
  await page.route('**/connectors/notion/databases', (route) => route.fulfill(json({ databases: [{ id: 'local-database', title: 'Local request database' }] })))
  await page.route('**/connectors/notion/config', (route) => { if (route.request().method() === 'PUT') notionDatabase = route.request().postDataJSON().databaseId; return route.fulfill(json({ databaseId: notionDatabase, ok: true })) })
  await page.route('**/connectors/sync', (route) => { notionSyncs++; assert.equal(notionDatabase, 'local-database'); return route.fulfill(json({ results: [{ connector: 'notion', scanned: 3, created: 3 }] })) })
  await profile()
  await profileScreen.getByText('Account', { exact: true }).click()
  await profileScreen.getByRole('button', { name: 'Tools', exact: true }).click()
  await page.getByLabel('Notion database', { exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Pull now', exact: true }).isDisabled(), true)
  await page.getByLabel('Notion database', { exact: true }).selectOption('local-database')
  assert.equal(await page.getByRole('button', { name: 'Pull now', exact: true }).isDisabled(), true)
  await page.getByRole('button', { name: 'Save database', exact: true }).click()
  await waitFor(() => page.getByRole('button', { name: 'Pull now', exact: true }).isEnabled(), 'Notion saved database did not enable sync')
  await page.getByRole('button', { name: 'Pull now', exact: true }).click()
  await page.getByText('3 new in your feed.', { exact: true }).waitFor()
  assert.equal(notionSyncs, 1)
  passed('Notion still requires a persisted database before sync (local HTTP fixtures only)')
  assert.deepEqual(errors, [], 'Browser errors or external requests occurred')
  passed('No browser runtime errors or external network requests')
  await writeFile(`${output}/checks.json`, JSON.stringify({ checkedAt: new Date().toISOString(), environment: 'Local Worker, disposable D1, Chromium; sample workspace isolated in memory; all external providers disabled', checks }, null, 2))
} catch (error) { await shot('failure').catch(() => {}); console.error((await page.locator('body').innerText().catch(() => '')).slice(-2500)); throw error }
finally { releaseRoute?.(); await browser.close() }
