// Local disposable environments only. Never writes production data or storage state.
import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
const require = createRequire(import.meta.url)
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const base = process.env.WEB_QA_URL || 'http://127.0.0.1:3000'
assert(['127.0.0.1', 'localhost', '[::1]'].includes(new URL(base).hostname), 'Browser QA requires a local disposable environment')
const output = process.env.WEB_QA_OUTPUT || '/tmp/honmaruai-web-qa/screenshots'
await mkdir(output, { recursive: true })
const browser = await chromium.launch({ headless: true })
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1, colorScheme: 'light' })
const page = await context.newPage(), errors = [], checks = []
let demoActive = false, demoBackendRequests = 0
await context.route('**/*', (route) => {
  const url = new URL(route.request().url())
  if (['http:', 'https:'].includes(url.protocol) && !['127.0.0.1', 'localhost', '[::1]'].includes(url.hostname)) { errors.push(`Blocked non-local request during QA: ${url.origin}`); return route.abort('blockedbyclient') }
  if (demoActive && /^\/(auth|me|members|ai\/route|connectors|invites|businesses|record)(\/|\?|$)/.test(url.pathname)) demoBackendRequests++
  return route.continue()
})
page.on('pageerror', (error) => errors.push(error.message))
page.on('websocket', () => { if (demoActive) demoBackendRequests++ })
const passed = (name) => { checks.push(name); console.log(`PASS ${name}`) }
const waitFor = async (condition, message) => { const end = Date.now() + 15000; while (Date.now() < end) { if (await condition()) return; await new Promise((resolve) => setTimeout(resolve, 100)) } throw new Error(message) }
const shot = (name) => page.screenshot({ path: `${output}/${name}.png` })
const rows = () => page.locator('.wb-request-row')
const nav = (name) => page.getByRole('navigation', { name: 'Main navigation', exact: true }).getByRole('button', { name, exact: true }).click()
const mobileNav = (name) => page.getByRole('navigation', { name: 'Mobile navigation', exact: true }).getByRole('button', { name, exact: true }).click()
try {
  await page.goto(base, { waitUntil: 'networkidle' })
  await page.getByRole('heading', { name: 'Sign in to your workspace' }).waitFor()
  await shot('auth-desktop')
  demoActive = true
  await page.getByRole('button', { name: 'Try the local demo' }).click()
  assert.equal(await rows().count(), 5)
  await shot('demo-inbox-desktop')
  await page.getByLabel('Search requests').fill('onboarding')
  assert.equal(await rows().count(), 1)
  await page.getByLabel('Clear search').click()
  await page.getByRole('button', { name: 'Filters', exact: true }).click()
  await page.getByLabel('Filter by type', { exact: true }).selectOption('notification')
  assert.equal(await rows().count(), 1)
  await page.getByLabel('Filter by type', { exact: true }).selectOption('all')
  await page.getByRole('button', { name: 'Filters', exact: true }).click()
  await page.getByLabel('Sort requests').selectOption('oldest')
  assert.match(await rows().first().innerText(), /launch check-in/)
  await page.getByLabel('Sort requests').selectOption('priority')
  passed('Search, type filter, real sorting, and five realistic sample requests')
  await rows().filter({ hasText: 'onboarding flow' }).click()
  await page.getByRole('button', { name: 'Complete task', exact: true }).click()
  assert.equal(await rows().count(), 4)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  assert.equal(await rows().count(), 5)
  await rows().filter({ hasText: 'Update the Acme renewal proposal' }).click()
  await page.getByRole('button', { name: 'Complete revision', exact: true }).click()
  assert.equal(await rows().count(), 4)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  assert.equal(await rows().count(), 5)
  passed('Sample task/revision completion and undo change local state')
  await nav('Sent'); assert.equal(await rows().count(), 1)
  await shot('demo-sent-desktop')
  await nav('Completed'); assert.equal(await rows().count(), 1)
  await shot('demo-completed-desktop')
  await nav('Inbox 5')
  await page.setViewportSize({ width: 390, height: 844 })
  await shot('demo-inbox-mobile')
  await rows().first().click()
  await shot('demo-detail-mobile')
  const geometry = await page.evaluate(() => ({ overflow: document.documentElement.scrollWidth > innerWidth, actionsBottom: document.querySelector('.wb-detail-actions').getBoundingClientRect().bottom, navTop: document.querySelector('.wb-mobile-nav').getBoundingClientRect().top }))
  assert.equal(geometry.overflow, false); assert(geometry.actionsBottom <= geometry.navTop + 1)
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' })
  await shot('demo-detail-mobile-dark')
  await page.getByRole('button', { name: 'Respond', exact: true }).click()
  await page.getByLabel('Your response').fill('The message is clear. Please include the final checklist.')
  await page.getByRole('button', { name: 'Send response', exact: true }).click()
  assert.equal(await rows().count(), 4)
  passed('Mobile list-to-detail, unobscured actions, dark mode, and sample response')
  await page.getByRole('button', { name: 'New request', exact: true }).click()
  await page.getByLabel('Recipient', { exact: true }).selectOption('sample:maya')
  await page.getByLabel('What needs to happen?').fill('Review the updated customer interview plan before Thursday.')
  await page.getByRole('button', { name: 'Review request', exact: true }).click()
  await page.getByLabel('Subject', { exact: true }).fill('Review the customer interview plan')
  await shot('demo-compose-mobile')
  await page.getByRole('button', { name: 'Create sample request', exact: true }).click()
  await waitFor(async () => await page.getByRole('dialog').count() === 0, 'Sample composer did not close')
  assert.equal(await rows().count(), 2)
  await mobileNav('Workspace')
  await page.getByRole('button', { name: 'Reset demo', exact: true }).click()
  await mobileNav('Inbox')
  assert.equal(await rows().count(), 5)
  await mobileNav('Workspace')
  await page.getByRole('button', { name: 'Exit demo', exact: true }).last().click()
  assert.equal(demoBackendRequests, 0, 'Demo contacted backend')
  demoActive = false
  passed('Sample recipient/preview/create/reset/exit with zero backend requests or sockets')
  await page.setViewportSize({ width: 1440, height: 1000 }); await page.emulateMedia({ colorScheme: 'light' })
  await page.getByRole('button', { name: 'Create an account', exact: true }).click()
  const email = `web-redesign-${Date.now()}@example.invalid`, password = 'Local-QA-only-2026!'
  await page.getByLabel('Full name').fill('Release Review')
  await page.getByLabel('Email address').fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  await page.getByRole('heading', { name: 'A clear inbox.' }).waitFor()
  await waitFor(() => page.getByText('Live updates connected', { exact: true }).isVisible(), 'Authenticated socket never joined')
  await shot('inbox-empty-desktop')
  passed('Real signup, authenticated WebSocket join, and setup-aware empty state')
  await page.getByRole('button', { name: 'New request', exact: true }).click()
  await waitFor(async () => await page.getByLabel('Recipient', { exact: true }).locator('option').count() > 1, 'Authenticated member list did not load')
  await page.getByLabel('Recipient', { exact: true }).selectOption({ label: 'Release Review (you)' })
  await page.getByLabel('What needs to happen?').fill('Please approve the launch brief by Friday. Budget: $2,400. The owner is Release Review.')
  await page.getByRole('button', { name: 'Prepare with AI', exact: true }).click()
  await page.getByRole('heading', { name: 'Review your request' }).waitFor()
  await page.getByLabel('Subject', { exact: true }).fill('Approve the launch brief')
  await page.getByLabel('Request type', { exact: true }).selectOption('approval')
  await page.getByLabel('Background', { exact: true }).fill('The brief has passed editorial review. Final sign-off is needed before production.')
  await shot('composer-preview-desktop')
  assert.equal(await rows().count(), 0, 'Preview sent prematurely')
  assert.equal(await page.locator('.workbench[inert]').count(), 1)
  passed('Explicit authenticated recipient, editable AI/fallback preview, and modal focus isolation')
  await page.getByRole('button', { name: 'Send request', exact: true }).click()
  await waitFor(async () => await page.getByRole('dialog').count() === 0, 'Delivery was not confirmed')
  assert.equal(await rows().count(), 1)
  await nav('Inbox 1')
  await shot('inbox-decision-desktop')
  await page.getByRole('button', { name: 'Approve', exact: true }).click()
  await waitFor(async () => await rows().count() === 0, 'Approval did not persist')
  await page.getByText('Response saved. The sender can see your decision.').waitFor()
  await nav('Completed')
  assert.equal(await rows().count(), 1)
  await page.getByRole('button', { name: 'Undo response', exact: true }).click()
  await waitFor(async () => await rows().count() === 0, 'Undo did not persist')
  await nav('Inbox 1')
  passed('Confirmed delivery, persisted approval, Completed view, and server-confirmed undo')
  await page.setViewportSize({ width: 390, height: 844 })
  await rows().first().click()
  await shot('inbox-decision-mobile')
  await page.getByRole('button', { name: 'Respond', exact: true }).click()
  await page.getByLabel('Your response').fill('Reviewed. Please include the final checklist.')
  await page.getByRole('button', { name: 'Send response', exact: true }).click()
  await waitFor(async () => await rows().count() === 0, 'Response did not persist')
  await mobileNav('Completed')
  await rows().first().click()
  await page.getByText('Reviewed. Please include the final checklist.', { exact: true }).waitFor()
  await page.reload({ waitUntil: 'networkidle' })
  await page.getByText('Reviewed. Please include the final checklist.', { exact: true }).waitFor()
  passed('Real mobile response and completed request survive reload')
  await page.setViewportSize({ width: 1440, height: 1000 })
  await nav('Workspace')
  await page.getByRole('heading', { name: /Team/ }).waitFor()
  await page.getByText('Release Review (you)', { exact: true }).waitFor()
  await shot('workspace-desktop')
  await page.getByRole('button', { name: 'Create invite code' }).click()
  await page.locator('.settings-invite code').waitFor()
  passed('Workspace loads actual team/account and creates a real invite code')
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await page.getByLabel('Email address').fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('heading', { name: 'A clear inbox.' }).waitFor()
  await nav('Completed'); assert.equal(await rows().count(), 1)
  passed('Sign-out and email re-login restore actual membership and saved decisions')
  let releaseRoute, routeStarted = false
  const gate = new Promise((resolve) => { releaseRoute = resolve })
  await page.route('**/ai/route', async (route) => { const response = await route.fetch(); routeStarted = true; await gate; await route.fulfill({ response }).catch(() => {}) })
  await page.getByRole('button', { name: 'New request', exact: true }).click()
  await page.getByLabel('Recipient', { exact: true }).selectOption({ label: 'Release Review (you)' })
  await page.getByLabel('What needs to happen?').fill('Please approve this intentionally delayed local request.')
  await page.getByRole('button', { name: 'Prepare with AI', exact: true }).click()
  await waitFor(async () => routeStarted, 'Delayed preparation never started')
  await page.keyboard.press('Escape'); releaseRoute()
  await new Promise((resolve) => setTimeout(resolve, 300))
  await nav('Sent'); assert.equal(await rows().count(), 1)
  passed('Closing pending AI preparation cancels stale preview without delivery')
  await page.unroute('**/ai/route')
  // Connector UI qualification uses explicit local HTTP fixtures. No external tool is contacted.
  let notionDatabase = null, notionSyncs = 0
  const json = (body) => ({ contentType: 'application/json', body: JSON.stringify(body) })
  await page.route('**/connectors', (route) => route.fulfill(json({ connectors: [{ id: 'notion', label: 'Notion', status: 'active' }] })))
  await page.route('**/connectors/notion/databases', (route) => route.fulfill(json({ databases: [{ id: 'local-database', title: 'Local request database' }] })))
  await page.route('**/connectors/notion/config', (route) => { if (route.request().method() === 'PUT') notionDatabase = route.request().postDataJSON().databaseId; return route.fulfill(json({ databaseId: notionDatabase, ok: true })) })
  await page.route('**/connectors/notion/sync', (route) => { notionSyncs++; assert.equal(notionDatabase, 'local-database'); return route.fulfill(json({ scanned: 3, created: 3 })) })
  await nav('Workspace')
  await page.getByLabel('Notion database', { exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Sync', exact: true }).isDisabled(), true)
  await page.getByLabel('Notion database', { exact: true }).selectOption('local-database')
  assert.equal(await page.getByRole('button', { name: 'Sync', exact: true }).isDisabled(), true)
  await page.getByRole('button', { name: 'Save database', exact: true }).click()
  await page.getByText('Notion database saved. You can now sync requests.').waitFor()
  await page.getByRole('button', { name: 'Sync', exact: true }).click()
  await page.getByText('Notion synced. 3 new requests.').waitFor()
  assert.equal(notionSyncs, 1)
  passed('Notion UI requires persisted database selection before sync (local HTTP fixtures only)')
  assert.deepEqual(errors, [], 'Browser runtime errors occurred')
  passed('No browser runtime errors or external network requests')
  await writeFile(`${output}/checks.json`, JSON.stringify({ checkedAt: new Date().toISOString(), environment: 'Local Worker, disposable D1, Chromium; sample workspace isolated in client memory', checks }, null, 2))
} catch (error) { await shot('failure').catch(() => {}); console.error((await page.locator('body').innerText().catch(() => '')).slice(-2500)); throw error }
finally { await browser.close() }
