name = "tiktokforwork"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "ORG_RELAY"
class_name = "OrgRelay"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["OrgRelay"]

[[d1_databases]]
binding = "DB"
database_name = "tiktokforwork"
database_id = "08d78a7f-45eb-4837-8393-4f7c92bf39cb"
